// Generated by ReScript, PLEASE EDIT WITH CARE

import Ava from "ava";
import * as Js_int from "rescript/lib/es6/js_int.js";
import * as $$Number from "../src/Number.bs.mjs";
import * as TestUtils from "./TestUtils.bs.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as PervasivesU from "rescript/lib/es6/pervasivesU.js";

var name = "Int32";

var valueShiftLeft = [
  1000000000,
  2000000000,
  -294967296,
  -589934592,
  -1179869184,
  1935228928,
  -424509440,
  -849018880,
  -1698037760,
  898891776,
  1797783552,
  -699400192,
  -1398800384,
  1497366528,
  -1300234240,
  1694498816,
  -905969664,
  -1811939328,
  671088640,
  1342177280,
  -1610612736,
  1073741824,
  -2147483648,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
];

var valueRotateShiftLeft = [
  1000000000,
  2000000000,
  -294967296,
  -589934591,
  -1179869181,
  1935228935,
  -424509426,
  -849018851,
  -1698037701,
  898891895,
  1797783790,
  -699399716,
  -1398799431,
  1497368435,
  -1300230426,
  1694506445,
  -905954406,
  -1811908811,
  671149675,
  1342299350,
  -1610368596,
  1074230105,
  -2146507086,
  1953125,
  3906250,
  7812500,
  15625000,
  31250000,
  62500000,
  125000000,
  250000000,
  500000000
];

var negZero = -0;

var zero = $$Number.Int32.zero;

var one = $$Number.Int32.one;

var fromIntExn = $$Number.Int32.fromIntExn;

var fromFloatExn = $$Number.Int32.fromFloatExn;

function randomValue() {
  return TestUtils.randomInt(Js_int.min, Js_int.max);
}

function randomLargerInt() {
  return TestUtils.randomInt(Js_int.max + 1.0, Js_int.max);
}

function randomSmallerInt() {
  return TestUtils.randomInt(Js_int.min, Js_int.min);
}

function testFn(fn) {
  fn(0);
  fn(negZero);
  fn(1);
  fn(1000000000);
  fn(-27852);
  fn(56331);
  fn(Js_int.min);
  fn(Js_int.min + 1 | 0);
  fn(Js_int.max);
  fn(Js_int.max - 1 | 0);
  TestUtils.loop100Fn(function () {
        fn(TestUtils.randomInt(Js_int.min, Js_int.max));
      });
}

Ava("test " + name + " sign", (function (t) {
        t.deepEqual($$Number.Int32.isSigned, true, undefined);
        t.deepEqual($$Number.Int32.isUnsigned, false, undefined);
      }));

Ava("test " + name + " bits", (function (t) {
        t.deepEqual($$Number.Int32.bits, 32, undefined);
      }));

Ava("test " + name + " from int", (function (t) {
        var testInRange = function (i) {
          var n = fromIntExn(i);
          t.deepEqual($$Number.Int32.fromInt(i), Caml_option.some(n), undefined);
          t.deepEqual(fromIntExn(i), n, undefined);
          t.deepEqual($$Number.Int32.fromIntClamped(i), n, undefined);
          t.deepEqual($$Number.Int32.fromIntUnsafe(i), n, undefined);
        };
        testFn(testInRange);
        testInRange(-1);
        testInRange(-1000000000);
        testInRange(-Js_int.max | 0);
      }));

Ava("test " + name + " to int", (function (t) {
        var testToInt = function (i) {
          var n = fromIntExn(i);
          var i$1 = i | 0;
          t.deepEqual($$Number.Int32.toInt(n), i$1, undefined);
          t.deepEqual($$Number.Int32.toIntExn(n), i$1, undefined);
          t.deepEqual($$Number.Int32.toIntClamped(n), i$1, undefined);
          t.deepEqual($$Number.Int32.toIntUnsafe(n), i$1, undefined);
        };
        testFn(testToInt);
        testToInt(-1);
        testToInt(-1000000000);
        testToInt(-Js_int.max | 0);
      }));

Ava("test " + name + " from float", (function (t) {
        var testIsIntegerAndInRange = function (i) {
          var n = fromIntExn(i);
          t.deepEqual($$Number.Int32.fromFloat(i), Caml_option.some(n), undefined);
          t.deepEqual(fromFloatExn(i), n, undefined);
          t.deepEqual($$Number.Int32.fromFloatClamped(i), n, undefined);
          t.deepEqual($$Number.Int32.fromFloatUnsafe(i), n, undefined);
        };
        testFn(testIsIntegerAndInRange);
        testIsIntegerAndInRange(-1);
        testIsIntegerAndInRange(-1000000000);
        testIsIntegerAndInRange(-Js_int.max | 0);
        var testOutOfRange = function (f, value) {
          t.deepEqual($$Number.Int32.fromFloat(f), undefined, undefined);
          TestUtils.assertOverflow(t, (function () {
                  return fromFloatExn(f);
                }));
          t.deepEqual($$Number.Int32.fromFloatClamped(f), fromIntExn(value), undefined);
        };
        testOutOfRange(Js_int.min - 1.0, Js_int.min);
        testOutOfRange(Js_int.max + 1.0, Js_int.max);
        testOutOfRange(Js_int.min - 1000000000, Js_int.min);
        testOutOfRange(Js_int.max + 1000000000, Js_int.max);
        TestUtils.loop100Fn(function () {
              testOutOfRange(Math.floor(TestUtils.randomFloat(Js_int.max + 1.0, TestUtils.maxSafeInteger)), Js_int.max);
            });
        TestUtils.loop100Fn(function () {
              testOutOfRange(Math.floor(TestUtils.randomFloat(TestUtils.minSafeInteger, Js_int.min - 1.0)), Js_int.min);
            });
        var testIsNotInteger = function (f, value) {
          t.deepEqual($$Number.Int32.fromFloat(f), undefined, undefined);
          TestUtils.assertInvalidArgument(t, (function () {
                  return fromFloatExn(f);
                }));
          t.deepEqual($$Number.Int32.fromFloatClamped(f), fromIntExn(value), undefined);
        };
        testIsNotInteger(1000000000 + 0.5, 1000000000);
        var f = - 1000000000 - 0.5;
        testIsNotInteger(f, f | 0);
        testIsNotInteger(Js_int.min + 0.1, Js_int.min + 1 | 0);
        testIsNotInteger(Number.NaN, 0);
        testIsNotInteger(PervasivesU.neg_infinity, Js_int.min);
        testIsNotInteger(PervasivesU.infinity, Js_int.max);
        testIsNotInteger(Js_int.min - 0.1, Js_int.min);
        testIsNotInteger(Js_int.max + 0.1, Js_int.max);
        testIsNotInteger(Js_int.max - 0.1, Js_int.max - 1 | 0);
        testIsNotInteger(Js_int.min - 1000000000 - 0.5, Js_int.min);
        testIsNotInteger(Js_int.max + 1000000000 + 0.5, Js_int.max);
      }));

Ava("test " + name + " to float", (function (t) {
        var testToFloat = function (i) {
          t.deepEqual($$Number.Int32.toFloat(fromFloatExn(i)), i, undefined);
        };
        testToFloat(1000000000);
        TestUtils.loop100Fn(function () {
              testToFloat(TestUtils.randomInt(Js_int.min, Js_int.max));
            });
      }));

Ava("test " + name + " from string", (function (t) {
        var testInRange = function (i, s) {
          var n = fromIntExn(i);
          t.deepEqual($$Number.Int32.fromString(s), Caml_option.some(n), undefined);
          t.deepEqual($$Number.Int32.fromStringExn(s), n, undefined);
          for(var radix = 2; radix <= 36; ++radix){
            var s$1 = i.toString(radix);
            t.deepEqual($$Number.Int32.fromStringWithRadix(s$1, radix), Caml_option.some(n), undefined);
            t.deepEqual($$Number.Int32.fromStringWithRadixExn(s$1, radix), n, undefined);
          }
          TestUtils.assertInvalidArgument(t, (function () {
                  return $$Number.Int32.fromStringWithRadixExn(s, 1);
                }));
          TestUtils.assertInvalidArgument(t, (function () {
                  return $$Number.Int32.fromStringWithRadixExn(s, 37);
                }));
        };
        testInRange(0, "0");
        testInRange(0, "-0");
        testInRange(1, "1");
        testInRange(1000000000, String(1000000000));
        testInRange(1000000000, String(1000000000 + 0.5));
        testInRange(Js_int.min, String(Js_int.min));
        testInRange(Js_int.max, String(Js_int.max));
        testInRange(Js_int.min + 1 | 0, String(Js_int.min + 1 | 0));
        testInRange(Js_int.max - 1 | 0, String(Js_int.max - 1 | 0));
        TestUtils.loop100Fn(function () {
              var value = TestUtils.randomInt(Js_int.min, Js_int.max);
              testInRange(value, String(value));
            });
        testInRange(-1000000000, String(-1000000000));
        testInRange(-1000000000, String(- 1000000000 - 0.5));
        testInRange(-Js_int.max | 0, String(-Js_int.max | 0));
        var testOutOfRange = function (f) {
          var s = String(f);
          t.deepEqual($$Number.Int32.fromString(s), undefined, undefined);
          TestUtils.assertOverflow(t, (function () {
                  return $$Number.Int32.fromStringExn(s);
                }));
          for(var radix = 2; radix <= 36; ++radix){
            var s$1 = f.toString(radix);
            t.deepEqual($$Number.Int32.fromStringWithRadix(s$1, radix), undefined, undefined);
            TestUtils.assertOverflow(t, (function(radix,s$1){
                return function () {
                  return $$Number.Int32.fromStringWithRadixExn(s$1, radix);
                }
                }(radix,s$1)));
          }
          TestUtils.assertInvalidArgument(t, (function () {
                  return $$Number.Int32.fromStringWithRadixExn(s, 1);
                }));
          TestUtils.assertInvalidArgument(t, (function () {
                  return $$Number.Int32.fromStringWithRadixExn(s, 37);
                }));
        };
        testOutOfRange(Js_int.min - 1.0);
        testOutOfRange(Js_int.max + 1.0);
        testOutOfRange(Js_int.min - 1000000000);
        testOutOfRange(Js_int.max + 1000000000);
        var testIsNotInteger = function (s) {
          t.deepEqual($$Number.Int32.fromString(s), undefined, undefined);
          TestUtils.assertInvalidArgument(t, (function () {
                  return $$Number.Int32.fromStringExn(s);
                }));
          for(var radix = 2; radix <= 10; ++radix){
            t.deepEqual($$Number.Int32.fromStringWithRadix(s, radix), undefined, undefined);
            TestUtils.assertInvalidArgument(t, (function(radix){
                return function () {
                  return $$Number.Int32.fromStringWithRadixExn(s, radix);
                }
                }(radix)));
          }
          TestUtils.assertInvalidArgument(t, (function () {
                  return $$Number.Int32.fromStringWithRadixExn(s, 1);
                }));
          TestUtils.assertInvalidArgument(t, (function () {
                  return $$Number.Int32.fromStringWithRadixExn(s, 37);
                }));
        };
        testIsNotInteger("NaN");
        testIsNotInteger("Infinity");
        testIsNotInteger("-Infinity");
        testIsNotInteger("foo");
        testIsNotInteger("b1");
      }));

Ava("test " + name + " to string", (function (t) {
        var testToString = function (i) {
          var s = String(i);
          var n = fromIntExn(i);
          t.deepEqual($$Number.Int32.toString(n), s, undefined);
          for(var radix = 2; radix <= 36; ++radix){
            var s$1 = i.toString(radix);
            t.deepEqual($$Number.Int32.toStringWithRadixExn(n, radix), s$1, undefined);
          }
          t.throws((function () {
                  return $$Number.Int32.toStringWithRadixExn(n, 1);
                }), undefined, undefined);
          t.throws((function () {
                  return $$Number.Int32.toStringWithRadixExn(n, 37);
                }), undefined, undefined);
        };
        testFn(testToString);
        var testToExponential = function (i) {
          var s = i.toExponential();
          var n = fromIntExn(i);
          t.deepEqual($$Number.Int32.toExponential(n), s, undefined);
          for(var digits = 0; digits <= 100; ++digits){
            var s$1 = i.toExponential(digits);
            t.deepEqual($$Number.Int32.toExponentialWithPrecisionExn(n, digits), s$1, undefined);
          }
          t.throws((function () {
                  return $$Number.Int32.toExponentialWithPrecisionExn(n, -1);
                }), undefined, undefined);
          t.throws((function () {
                  return $$Number.Int32.toExponentialWithPrecisionExn(n, 101);
                }), undefined, undefined);
        };
        testFn(testToExponential);
        var testToPrecision = function (i) {
          var s = i.toPrecision();
          var n = fromIntExn(i);
          t.deepEqual($$Number.Int32.toPrecision(n), s, undefined);
          for(var digits = 1; digits <= 100; ++digits){
            var s$1 = i.toPrecision(digits);
            t.deepEqual($$Number.Int32.toPrecisionWithPrecisionExn(n, digits), s$1, undefined);
          }
          t.throws((function () {
                  return $$Number.Int32.toPrecisionWithPrecisionExn(n, 0);
                }), undefined, undefined);
          t.throws((function () {
                  return $$Number.Int32.toPrecisionWithPrecisionExn(n, 101);
                }), undefined, undefined);
        };
        testFn(testToPrecision);
      }));

Ava("test " + name + " zero", (function (t) {
        t.deepEqual(zero, fromIntExn(0), undefined);
        t.deepEqual(zero, fromFloatExn(0.0), undefined);
        t.deepEqual(zero, fromFloatExn(-0.0), undefined);
      }));

Ava("test " + name + " one", (function (t) {
        t.deepEqual(one, fromIntExn(1), undefined);
        t.deepEqual(one, fromFloatExn(1.0), undefined);
      }));

Ava("test " + name + " range", (function (t) {
        t.deepEqual($$Number.Int32.minValue, fromIntExn(Js_int.min), undefined);
        t.deepEqual($$Number.Int32.minValue, fromFloatExn(Js_int.min), undefined);
        t.deepEqual($$Number.Int32.maxValue, fromIntExn(Js_int.max), undefined);
        t.deepEqual($$Number.Int32.maxValue, fromFloatExn(Js_int.max), undefined);
      }));

Ava("test " + name + " comparison", (function (t) {
        var testCompare = function (less, greater) {
          var less$1 = fromIntExn(less);
          var greater$1 = fromIntExn(greater);
          var value = fromIntExn(1000000000);
          var minValue = fromIntExn(Js_int.min);
          var maxValue = fromIntExn(Js_int.max);
          t.deepEqual($$Number.Int32.compare(less$1, greater$1), -1, undefined);
          t.deepEqual($$Number.Int32.compare(greater$1, less$1), 1, undefined);
          t.deepEqual($$Number.Int32.compare(less$1, less$1), 0, undefined);
          t.deepEqual($$Number.Int32.compare(greater$1, greater$1), 0, undefined);
          t.deepEqual($$Number.Int32.compareExn(less$1, greater$1), -1, undefined);
          t.deepEqual($$Number.Int32.compareExn(greater$1, less$1), 1, undefined);
          t.deepEqual($$Number.Int32.compareExn(less$1, less$1), 0, undefined);
          t.deepEqual($$Number.Int32.compareExn(greater$1, greater$1), 0, undefined);
          t.true($$Number.Int32.eq(less$1, less$1), undefined);
          t.true($$Number.Int32.eq(greater$1, greater$1), undefined);
          t.false($$Number.Int32.eq(less$1, greater$1), undefined);
          t.false($$Number.Int32.eq(greater$1, less$1), undefined);
          t.true($$Number.Int32.ne(less$1, greater$1), undefined);
          t.true($$Number.Int32.ne(greater$1, less$1), undefined);
          t.false($$Number.Int32.ne(less$1, less$1), undefined);
          t.false($$Number.Int32.ne(greater$1, greater$1), undefined);
          t.true($$Number.Int32.lt(less$1, greater$1), undefined);
          t.false($$Number.Int32.lt(greater$1, less$1), undefined);
          t.false($$Number.Int32.lt(less$1, less$1), undefined);
          t.false($$Number.Int32.lt(greater$1, greater$1), undefined);
          t.true($$Number.Int32.le(less$1, greater$1), undefined);
          t.false($$Number.Int32.le(greater$1, less$1), undefined);
          t.true($$Number.Int32.le(less$1, less$1), undefined);
          t.true($$Number.Int32.le(greater$1, greater$1), undefined);
          t.true($$Number.Int32.gt(greater$1, less$1), undefined);
          t.false($$Number.Int32.gt(less$1, greater$1), undefined);
          t.false($$Number.Int32.gt(less$1, less$1), undefined);
          t.false($$Number.Int32.gt(greater$1, greater$1), undefined);
          t.true($$Number.Int32.ge(greater$1, less$1), undefined);
          t.false($$Number.Int32.ge(less$1, greater$1), undefined);
          t.true($$Number.Int32.ge(less$1, less$1), undefined);
          t.true($$Number.Int32.ge(greater$1, greater$1), undefined);
          t.deepEqual($$Number.Int32.min(less$1, greater$1), less$1, undefined);
          t.deepEqual($$Number.Int32.min(greater$1, less$1), less$1, undefined);
          t.deepEqual($$Number.Int32.min(less$1, less$1), less$1, undefined);
          t.deepEqual($$Number.Int32.min(greater$1, greater$1), greater$1, undefined);
          t.deepEqual($$Number.Int32.minMany([less$1]), Caml_option.some(less$1), undefined);
          t.deepEqual($$Number.Int32.minMany([
                    less$1,
                    greater$1
                  ]), Caml_option.some(less$1), undefined);
          t.deepEqual($$Number.Int32.minMany([
                    greater$1,
                    less$1
                  ]), Caml_option.some(less$1), undefined);
          t.deepEqual($$Number.Int32.minMany([
                    less$1,
                    value,
                    greater$1,
                    minValue,
                    maxValue
                  ]), Caml_option.some(minValue), undefined);
          t.deepEqual($$Number.Int32.minManyExn([less$1]), less$1, undefined);
          t.deepEqual($$Number.Int32.minManyExn([
                    less$1,
                    greater$1
                  ]), less$1, undefined);
          t.deepEqual($$Number.Int32.minManyExn([
                    greater$1,
                    less$1
                  ]), less$1, undefined);
          t.deepEqual($$Number.Int32.minManyExn([
                    minValue,
                    maxValue,
                    less$1,
                    value,
                    greater$1
                  ]), minValue, undefined);
          t.deepEqual($$Number.Int32.minManyUnsafe([less$1]), less$1, undefined);
          t.deepEqual($$Number.Int32.minManyUnsafe([
                    less$1,
                    greater$1
                  ]), less$1, undefined);
          t.deepEqual($$Number.Int32.minManyUnsafe([
                    greater$1,
                    less$1
                  ]), less$1, undefined);
          t.deepEqual($$Number.Int32.minManyUnsafe([
                    less$1,
                    minValue,
                    maxValue,
                    value,
                    greater$1
                  ]), minValue, undefined);
          t.deepEqual($$Number.Int32.max(less$1, greater$1), greater$1, undefined);
          t.deepEqual($$Number.Int32.max(greater$1, less$1), greater$1, undefined);
          t.deepEqual($$Number.Int32.max(less$1, less$1), less$1, undefined);
          t.deepEqual($$Number.Int32.max(greater$1, greater$1), greater$1, undefined);
          t.deepEqual($$Number.Int32.maxMany([less$1]), Caml_option.some(less$1), undefined);
          t.deepEqual($$Number.Int32.maxMany([
                    less$1,
                    greater$1
                  ]), Caml_option.some(greater$1), undefined);
          t.deepEqual($$Number.Int32.maxMany([
                    greater$1,
                    less$1
                  ]), Caml_option.some(greater$1), undefined);
          t.deepEqual($$Number.Int32.maxMany([
                    less$1,
                    value,
                    greater$1,
                    minValue,
                    maxValue
                  ]), Caml_option.some(maxValue), undefined);
          t.deepEqual($$Number.Int32.maxManyExn([less$1]), less$1, undefined);
          t.deepEqual($$Number.Int32.maxManyExn([
                    less$1,
                    greater$1
                  ]), greater$1, undefined);
          t.deepEqual($$Number.Int32.maxManyExn([
                    greater$1,
                    less$1
                  ]), greater$1, undefined);
          t.deepEqual($$Number.Int32.maxManyExn([
                    minValue,
                    maxValue,
                    less$1,
                    value,
                    greater$1
                  ]), maxValue, undefined);
          t.deepEqual($$Number.Int32.maxManyUnsafe([less$1]), less$1, undefined);
          t.deepEqual($$Number.Int32.maxManyUnsafe([
                    less$1,
                    greater$1
                  ]), greater$1, undefined);
          t.deepEqual($$Number.Int32.maxManyUnsafe([
                    greater$1,
                    less$1
                  ]), greater$1, undefined);
          t.deepEqual($$Number.Int32.maxManyUnsafe([
                    less$1,
                    minValue,
                    maxValue,
                    value,
                    greater$1
                  ]), maxValue, undefined);
        };
        testCompare(-27852, 56331);
        TestUtils.loop100Fn(function () {
              var less = TestUtils.randomInt(Js_int.min, Js_int.max);
              var greater = TestUtils.randomInt(less + 1.0, Js_int.max + 1.0);
              testCompare(less, greater);
            });
        var zero = fromIntExn(0);
        var negZero$1 = fromIntExn(negZero);
        t.true($$Number.Int32.eq(zero, negZero$1), undefined);
        t.true($$Number.Int32.le(zero, negZero$1), undefined);
        t.true($$Number.Int32.ge(zero, negZero$1), undefined);
        t.false($$Number.Int32.lt(zero, negZero$1), undefined);
        t.false($$Number.Int32.gt(zero, negZero$1), undefined);
        t.deepEqual($$Number.Int32.minMany([]), undefined, undefined);
        TestUtils.assertInvalidArgument(t, (function () {
                return $$Number.Int32.minManyExn([]);
              }));
        t.deepEqual($$Number.Int32.maxMany([]), undefined, undefined);
        TestUtils.assertInvalidArgument(t, (function () {
                return $$Number.Int32.maxManyExn([]);
              }));
      }));

Ava("test " + name + " addition", (function (t) {
        var testInRange = function (a, b) {
          if (a !== Js_int.min) {
            var negA = fromIntExn(-a | 0);
            var a$1 = fromIntExn(a);
            t.deepEqual($$Number.Int32.add(a$1, negA), Caml_option.some(zero), undefined);
            t.deepEqual($$Number.Int32.add(a$1, negA), $$Number.Int32.add(negA, a$1), undefined);
            t.deepEqual($$Number.Int32.addExn(a$1, negA), zero, undefined);
            t.deepEqual($$Number.Int32.addExn(a$1, negA), $$Number.Int32.addExn(negA, a$1), undefined);
            t.deepEqual($$Number.Int32.addClamped(a$1, negA), zero, undefined);
            t.deepEqual($$Number.Int32.addClamped(a$1, negA), $$Number.Int32.addClamped(negA, a$1), undefined);
            t.deepEqual($$Number.Int32.addUnsafe(a$1, negA), zero, undefined);
            t.deepEqual($$Number.Int32.addUnsafe(a$1, negA), $$Number.Int32.addUnsafe(negA, a$1), undefined);
          }
          if (b !== Js_int.min) {
            var negB = fromIntExn(-b | 0);
            var b$1 = fromIntExn(b);
            t.deepEqual($$Number.Int32.add(b$1, negB), Caml_option.some(zero), undefined);
            t.deepEqual($$Number.Int32.add(b$1, negB), $$Number.Int32.add(negB, b$1), undefined);
            t.deepEqual($$Number.Int32.addExn(b$1, negB), zero, undefined);
            t.deepEqual($$Number.Int32.addExn(b$1, negB), $$Number.Int32.addExn(negB, b$1), undefined);
            t.deepEqual($$Number.Int32.addClamped(b$1, negB), zero, undefined);
            t.deepEqual($$Number.Int32.addClamped(b$1, negB), $$Number.Int32.addClamped(negB, b$1), undefined);
            t.deepEqual($$Number.Int32.addUnsafe(b$1, negB), zero, undefined);
            t.deepEqual($$Number.Int32.addUnsafe(b$1, negB), $$Number.Int32.addUnsafe(negB, b$1), undefined);
          }
          var result = fromIntExn(a + b | 0);
          var a$2 = fromIntExn(a);
          var b$2 = fromIntExn(b);
          t.deepEqual($$Number.Int32.add(a$2, b$2), Caml_option.some(result), undefined);
          t.deepEqual($$Number.Int32.add(a$2, b$2), $$Number.Int32.add(b$2, a$2), undefined);
          t.deepEqual($$Number.Int32.addExn(a$2, b$2), result, undefined);
          t.deepEqual($$Number.Int32.addExn(a$2, b$2), $$Number.Int32.addExn(b$2, a$2), undefined);
          t.deepEqual($$Number.Int32.addClamped(a$2, b$2), result, undefined);
          t.deepEqual($$Number.Int32.addClamped(a$2, b$2), $$Number.Int32.addClamped(b$2, a$2), undefined);
          t.deepEqual($$Number.Int32.addUnsafe(a$2, b$2), result, undefined);
          t.deepEqual($$Number.Int32.addUnsafe(a$2, b$2), $$Number.Int32.addUnsafe(b$2, a$2), undefined);
          t.deepEqual($$Number.Int32.add(a$2, zero), Caml_option.some(a$2), undefined);
          t.deepEqual($$Number.Int32.add(a$2, zero), $$Number.Int32.add(zero, a$2), undefined);
          t.deepEqual($$Number.Int32.addExn(a$2, zero), a$2, undefined);
          t.deepEqual($$Number.Int32.addExn(a$2, zero), $$Number.Int32.addExn(zero, a$2), undefined);
          t.deepEqual($$Number.Int32.addClamped(a$2, zero), a$2, undefined);
          t.deepEqual($$Number.Int32.addClamped(a$2, zero), $$Number.Int32.addClamped(zero, a$2), undefined);
          t.deepEqual($$Number.Int32.addUnsafe(a$2, zero), a$2, undefined);
          t.deepEqual($$Number.Int32.addUnsafe(a$2, zero), $$Number.Int32.addUnsafe(zero, a$2), undefined);
          t.deepEqual($$Number.Int32.add(b$2, zero), Caml_option.some(b$2), undefined);
          t.deepEqual($$Number.Int32.add(b$2, zero), $$Number.Int32.add(zero, b$2), undefined);
          t.deepEqual($$Number.Int32.addExn(b$2, zero), b$2, undefined);
          t.deepEqual($$Number.Int32.addExn(b$2, zero), $$Number.Int32.addExn(zero, b$2), undefined);
          t.deepEqual($$Number.Int32.addClamped(b$2, zero), b$2, undefined);
          t.deepEqual($$Number.Int32.addClamped(b$2, zero), $$Number.Int32.addClamped(zero, b$2), undefined);
          t.deepEqual($$Number.Int32.addUnsafe(b$2, zero), b$2, undefined);
          t.deepEqual($$Number.Int32.addUnsafe(b$2, zero), $$Number.Int32.addUnsafe(zero, b$2), undefined);
        };
        testInRange(-27852, 56331);
        testInRange(Js_int.min, 0);
        testInRange(Js_int.max, 0);
        testInRange(Js_int.min, 1);
        testInRange(Js_int.max, -1);
        var testOutOfRange = function (a, b, value) {
          var a$1 = fromIntExn(a);
          var b$1 = fromIntExn(b);
          var value$1 = fromIntExn(value);
          t.deepEqual($$Number.Int32.add(a$1, b$1), undefined, undefined);
          t.deepEqual($$Number.Int32.add(b$1, a$1), undefined, undefined);
          TestUtils.assertOverflow(t, (function () {
                  return $$Number.Int32.addExn(a$1, b$1);
                }));
          TestUtils.assertOverflow(t, (function () {
                  return $$Number.Int32.addExn(b$1, a$1);
                }));
          t.deepEqual($$Number.Int32.addClamped(a$1, b$1), value$1, undefined);
          t.deepEqual($$Number.Int32.addClamped(b$1, a$1), value$1, undefined);
        };
        testOutOfRange(Js_int.min, -1, Js_int.min);
        testOutOfRange(Js_int.min, -1000000000, Js_int.min);
        testOutOfRange(Js_int.max, 1, Js_int.max);
        testOutOfRange(Js_int.max, 1000000000, Js_int.max);
        TestUtils.loop100Fn(function () {
              var a = TestUtils.randomInt(Js_int.min, Js_int.max);
              var b = TestUtils.randomInt(Js_int.min, Js_int.max);
              var result = a + b;
              if (result < Js_int.min) {
                testOutOfRange(a, b, Js_int.min);
              } else if (result > Js_int.max) {
                testOutOfRange(a, b, Js_int.max);
              } else {
                testInRange(a, b);
              }
              testInRange(a, 1);
              testInRange(b, 1);
            });
      }));

Ava("test " + name + " subtraction", (function (t) {
        var testInRange = function (a, b) {
          var result = fromIntExn(a - b | 0);
          var a$1 = fromIntExn(a);
          var b$1 = fromIntExn(b);
          t.deepEqual($$Number.Int32.sub(a$1, b$1), Caml_option.some(result), undefined);
          t.deepEqual($$Number.Int32.subExn(a$1, b$1), result, undefined);
          t.deepEqual($$Number.Int32.subClamped(a$1, b$1), result, undefined);
          t.deepEqual($$Number.Int32.subUnsafe(a$1, b$1), result, undefined);
          t.deepEqual($$Number.Int32.sub(a$1, result), Caml_option.some(b$1), undefined);
          t.deepEqual($$Number.Int32.subExn(a$1, result), b$1, undefined);
          t.deepEqual($$Number.Int32.subClamped(a$1, result), b$1, undefined);
          t.deepEqual($$Number.Int32.subUnsafe(a$1, result), b$1, undefined);
          t.deepEqual($$Number.Int32.sub(a$1, a$1), Caml_option.some(zero), undefined);
          t.deepEqual($$Number.Int32.subExn(a$1, a$1), zero, undefined);
          t.deepEqual($$Number.Int32.subClamped(a$1, a$1), zero, undefined);
          t.deepEqual($$Number.Int32.subUnsafe(a$1, a$1), zero, undefined);
          t.deepEqual($$Number.Int32.sub(a$1, zero), Caml_option.some(a$1), undefined);
          t.deepEqual($$Number.Int32.subExn(a$1, zero), a$1, undefined);
          t.deepEqual($$Number.Int32.subClamped(a$1, zero), a$1, undefined);
          t.deepEqual($$Number.Int32.subUnsafe(a$1, zero), a$1, undefined);
          t.deepEqual($$Number.Int32.sub(b$1, b$1), Caml_option.some(zero), undefined);
          t.deepEqual($$Number.Int32.subExn(b$1, b$1), zero, undefined);
          t.deepEqual($$Number.Int32.subClamped(b$1, b$1), zero, undefined);
          t.deepEqual($$Number.Int32.subUnsafe(b$1, b$1), zero, undefined);
          t.deepEqual($$Number.Int32.sub(b$1, zero), Caml_option.some(b$1), undefined);
          t.deepEqual($$Number.Int32.subExn(b$1, zero), b$1, undefined);
          t.deepEqual($$Number.Int32.subClamped(b$1, zero), b$1, undefined);
          t.deepEqual($$Number.Int32.subUnsafe(b$1, zero), b$1, undefined);
        };
        testInRange(56331, -27852);
        testInRange(Js_int.min, 0);
        testInRange(Js_int.max, 0);
        testInRange(Js_int.max, 1);
        testInRange(-27852, 56331);
        testInRange(Js_int.min, -1);
        testInRange(0, Js_int.max);
        var testOutOfRange = function (a, b, value) {
          var a$1 = fromIntExn(a);
          var b$1 = fromIntExn(b);
          t.deepEqual($$Number.Int32.sub(a$1, b$1), undefined, undefined);
          TestUtils.assertOverflow(t, (function () {
                  return $$Number.Int32.subExn(a$1, b$1);
                }));
          t.deepEqual($$Number.Int32.subClamped(a$1, b$1), fromIntExn(value), undefined);
        };
        testOutOfRange(Js_int.min, 1, Js_int.min);
        testOutOfRange(Js_int.min, 1000000000, Js_int.min);
        testOutOfRange(Js_int.max, -1, Js_int.max);
        testOutOfRange(Js_int.max, -1000000000, Js_int.max);
        TestUtils.loop100Fn(function () {
              var a = TestUtils.randomInt(Js_int.min, Js_int.max);
              var b = TestUtils.randomInt(Js_int.min, Js_int.max);
              var result = a - b;
              if (result < Js_int.min) {
                testOutOfRange(a, b, Js_int.min);
              } else if (result > Js_int.max) {
                testOutOfRange(a, b, Js_int.max);
              } else {
                testInRange(a, b);
              }
              var result$1 = b - a;
              if (result$1 < Js_int.min) {
                return testOutOfRange(b, a, Js_int.min);
              } else if (result$1 > Js_int.max) {
                return testOutOfRange(b, a, Js_int.max);
              } else {
                return testInRange(b, a);
              }
            });
      }));

Ava("test " + name + " multiplication", (function (t) {
        var testInRange = function (a, b) {
          var result = fromIntExn(Math.imul(a, b));
          var a$1 = fromIntExn(a);
          var b$1 = fromIntExn(b);
          t.deepEqual($$Number.Int32.mul(a$1, b$1), Caml_option.some(result), undefined);
          t.deepEqual($$Number.Int32.mul(a$1, b$1), $$Number.Int32.mul(b$1, a$1), undefined);
          t.deepEqual($$Number.Int32.mulExn(a$1, b$1), result, undefined);
          t.deepEqual($$Number.Int32.mulExn(a$1, b$1), $$Number.Int32.mulExn(b$1, a$1), undefined);
          t.deepEqual($$Number.Int32.mulClamped(a$1, b$1), result, undefined);
          t.deepEqual($$Number.Int32.mulClamped(a$1, b$1), $$Number.Int32.mulClamped(b$1, a$1), undefined);
          t.deepEqual($$Number.Int32.mulUnsafe(a$1, b$1), result, undefined);
          t.deepEqual($$Number.Int32.mulUnsafe(a$1, b$1), $$Number.Int32.mulUnsafe(b$1, a$1), undefined);
          t.deepEqual($$Number.Int32.mul(a$1, zero), Caml_option.some(zero), undefined);
          t.deepEqual($$Number.Int32.mul(a$1, zero), $$Number.Int32.mul(zero, a$1), undefined);
          t.deepEqual($$Number.Int32.mulExn(a$1, zero), zero, undefined);
          t.deepEqual($$Number.Int32.mulExn(a$1, zero), $$Number.Int32.mulExn(zero, a$1), undefined);
          t.deepEqual($$Number.Int32.mulClamped(a$1, zero), zero, undefined);
          t.deepEqual($$Number.Int32.mulClamped(a$1, zero), $$Number.Int32.mulClamped(zero, a$1), undefined);
          t.deepEqual($$Number.Int32.mulUnsafe(a$1, zero), zero, undefined);
          t.deepEqual($$Number.Int32.mulUnsafe(a$1, zero), $$Number.Int32.mulUnsafe(zero, a$1), undefined);
          t.deepEqual($$Number.Int32.mul(a$1, one), Caml_option.some(a$1), undefined);
          t.deepEqual($$Number.Int32.mul(a$1, one), $$Number.Int32.mul(one, a$1), undefined);
          t.deepEqual($$Number.Int32.mulExn(a$1, one), a$1, undefined);
          t.deepEqual($$Number.Int32.mulExn(a$1, one), $$Number.Int32.mulExn(one, a$1), undefined);
          t.deepEqual($$Number.Int32.mulClamped(a$1, one), a$1, undefined);
          t.deepEqual($$Number.Int32.mulClamped(a$1, one), $$Number.Int32.mulClamped(one, a$1), undefined);
          t.deepEqual($$Number.Int32.mulUnsafe(a$1, one), a$1, undefined);
          t.deepEqual($$Number.Int32.mulUnsafe(a$1, one), $$Number.Int32.mulUnsafe(one, a$1), undefined);
          t.deepEqual($$Number.Int32.mul(b$1, zero), Caml_option.some(zero), undefined);
          t.deepEqual($$Number.Int32.mul(b$1, zero), $$Number.Int32.mul(zero, b$1), undefined);
          t.deepEqual($$Number.Int32.mulExn(b$1, zero), zero, undefined);
          t.deepEqual($$Number.Int32.mulExn(b$1, zero), $$Number.Int32.mulExn(zero, b$1), undefined);
          t.deepEqual($$Number.Int32.mulClamped(b$1, zero), zero, undefined);
          t.deepEqual($$Number.Int32.mulClamped(b$1, zero), $$Number.Int32.mulClamped(zero, b$1), undefined);
          t.deepEqual($$Number.Int32.mulUnsafe(b$1, zero), zero, undefined);
          t.deepEqual($$Number.Int32.mulUnsafe(b$1, zero), $$Number.Int32.mulUnsafe(zero, b$1), undefined);
          t.deepEqual($$Number.Int32.mul(b$1, one), Caml_option.some(b$1), undefined);
          t.deepEqual($$Number.Int32.mul(b$1, one), $$Number.Int32.mul(one, b$1), undefined);
          t.deepEqual($$Number.Int32.mulExn(b$1, one), b$1, undefined);
          t.deepEqual($$Number.Int32.mulExn(b$1, one), $$Number.Int32.mulExn(one, b$1), undefined);
          t.deepEqual($$Number.Int32.mulClamped(b$1, one), b$1, undefined);
          t.deepEqual($$Number.Int32.mulClamped(b$1, one), $$Number.Int32.mulClamped(one, b$1), undefined);
          t.deepEqual($$Number.Int32.mulUnsafe(b$1, one), b$1, undefined);
          t.deepEqual($$Number.Int32.mulUnsafe(b$1, one), $$Number.Int32.mulUnsafe(one, b$1), undefined);
        };
        testInRange(-27852, 56331);
        testInRange(Js_int.min, 0);
        testInRange(Js_int.max, 0);
        testInRange(Js_int.min, 1);
        testInRange(Js_int.max, 1);
        testInRange(Js_int.min + 1 | 0, 1);
        testInRange(Js_int.max - 1 | 0, 1);
        testInRange(-Js_int.max | 0, 1);
        testInRange(Js_int.max, -1);
        var testOutOfRange = function (a, b, value) {
          var a$1 = fromIntExn(a);
          var b$1 = fromIntExn(b);
          var value$1 = fromIntExn(value);
          t.deepEqual($$Number.Int32.mul(a$1, b$1), undefined, undefined);
          t.deepEqual($$Number.Int32.mul(b$1, a$1), undefined, undefined);
          TestUtils.assertOverflow(t, (function () {
                  return $$Number.Int32.mulExn(a$1, b$1);
                }));
          TestUtils.assertOverflow(t, (function () {
                  return $$Number.Int32.mulExn(b$1, a$1);
                }));
          t.deepEqual($$Number.Int32.mulClamped(a$1, b$1), value$1, undefined);
          t.deepEqual($$Number.Int32.mulClamped(b$1, a$1), value$1, undefined);
        };
        testOutOfRange(Js_int.max, 2, Js_int.max);
        testOutOfRange(Js_int.max, 1000000000, Js_int.max);
        testOutOfRange(Js_int.min, 2, Js_int.min);
        testOutOfRange(Js_int.min, 1000000000, Js_int.min);
        testOutOfRange(Js_int.min, -1, Js_int.max);
        testOutOfRange(Js_int.max, -2, Js_int.min);
        testOutOfRange(Js_int.min, -1000000000, Js_int.max);
        testOutOfRange(Js_int.max, -1000000000, Js_int.min);
        TestUtils.loop100Fn(function () {
              var a = TestUtils.randomInt(Js_int.min, Js_int.max);
              var b = TestUtils.randomInt(Js_int.min, Js_int.max);
              var result = a * b;
              if (result < Js_int.min) {
                return testOutOfRange(a, b, Js_int.min);
              } else if (result > Js_int.max) {
                return testOutOfRange(a, b, Js_int.max);
              } else {
                return testInRange(a, b);
              }
            });
      }));

Ava("test " + name + " division", (function (t) {
        var testNotDividedByZero = function (a, b) {
          var negOne = fromIntExn(-1);
          if (a !== Js_int.min) {
            var negA = fromIntExn(-a | 0);
            var a$1 = fromIntExn(a);
            t.deepEqual($$Number.Int32.div(a$1, negOne), Caml_option.some(negA), undefined);
            t.deepEqual($$Number.Int32.divExn(a$1, negOne), negA, undefined);
            t.deepEqual($$Number.Int32.divUnsafe(a$1, negOne), negA, undefined);
          }
          if (b !== Js_int.min) {
            var negB = fromIntExn(-b | 0);
            var b$1 = fromIntExn(b);
            t.deepEqual($$Number.Int32.div(b$1, negOne), Caml_option.some(negB), undefined);
            t.deepEqual($$Number.Int32.divExn(b$1, negOne), negB, undefined);
            t.deepEqual($$Number.Int32.divUnsafe(b$1, negOne), negB, undefined);
          }
          if (a !== 0) {
            var result = fromIntExn(Caml_int32.div(b, a));
            var a$2 = fromIntExn(a);
            var b$2 = fromIntExn(b);
            t.deepEqual($$Number.Int32.div(b$2, a$2), Caml_option.some(result), undefined);
            t.deepEqual($$Number.Int32.divExn(b$2, a$2), result, undefined);
            t.deepEqual($$Number.Int32.divUnsafe(b$2, a$2), result, undefined);
            t.deepEqual($$Number.Int32.div(a$2, a$2), Caml_option.some(one), undefined);
            t.deepEqual($$Number.Int32.divExn(a$2, a$2), one, undefined);
            t.deepEqual($$Number.Int32.divUnsafe(a$2, a$2), one, undefined);
            t.deepEqual($$Number.Int32.div(zero, a$2), Caml_option.some(zero), undefined);
            t.deepEqual($$Number.Int32.divExn(zero, a$2), zero, undefined);
            t.deepEqual($$Number.Int32.divUnsafe(zero, a$2), zero, undefined);
          }
          if (b !== 0) {
            var result$1 = fromIntExn(Caml_int32.div(a, b));
            var a$3 = fromIntExn(a);
            var b$3 = fromIntExn(b);
            t.deepEqual($$Number.Int32.div(a$3, b$3), Caml_option.some(result$1), undefined);
            t.deepEqual($$Number.Int32.divExn(a$3, b$3), result$1, undefined);
            t.deepEqual($$Number.Int32.divUnsafe(a$3, b$3), result$1, undefined);
            t.deepEqual($$Number.Int32.div(b$3, b$3), Caml_option.some(one), undefined);
            t.deepEqual($$Number.Int32.divExn(b$3, b$3), one, undefined);
            t.deepEqual($$Number.Int32.divUnsafe(b$3, b$3), one, undefined);
            t.deepEqual($$Number.Int32.div(zero, b$3), Caml_option.some(zero), undefined);
            t.deepEqual($$Number.Int32.divExn(zero, b$3), zero, undefined);
            t.deepEqual($$Number.Int32.divUnsafe(zero, b$3), zero, undefined);
          }
          var a$4 = fromIntExn(a);
          var b$4 = fromIntExn(b);
          t.deepEqual($$Number.Int32.div(a$4, one), Caml_option.some(a$4), undefined);
          t.deepEqual($$Number.Int32.divExn(a$4, one), a$4, undefined);
          t.deepEqual($$Number.Int32.divUnsafe(a$4, one), a$4, undefined);
          t.deepEqual($$Number.Int32.div(b$4, one), Caml_option.some(b$4), undefined);
          t.deepEqual($$Number.Int32.divExn(b$4, one), b$4, undefined);
          t.deepEqual($$Number.Int32.divUnsafe(b$4, one), b$4, undefined);
        };
        testNotDividedByZero(0, 1000000000);
        testNotDividedByZero(negZero, 1000000000);
        testNotDividedByZero(-27852, 56331);
        testNotDividedByZero(Js_int.min, -27852);
        testNotDividedByZero(Js_int.min, 56331);
        testNotDividedByZero(Js_int.max, -27852);
        testNotDividedByZero(Js_int.max, 56331);
        testNotDividedByZero(-27852, 2);
        testNotDividedByZero(56331, 2);
        testNotDividedByZero(Js_int.min, 2);
        testNotDividedByZero(Js_int.max, 2);
        testNotDividedByZero(Js_int.min + 1 | 0, 2);
        testNotDividedByZero(Js_int.max - 1 | 0, 2);
        testNotDividedByZero(-27852, -56331);
        testNotDividedByZero(56331, 27852);
        testNotDividedByZero(27852, -56331);
        testNotDividedByZero(Js_int.min, 27852);
        testNotDividedByZero(Js_int.min, -56331);
        testNotDividedByZero(Js_int.max, 27852);
        testNotDividedByZero(Js_int.max, -56331);
        testNotDividedByZero(-Js_int.max | 0, 27852);
        testNotDividedByZero(-Js_int.max | 0, -56331);
        testNotDividedByZero(-27852, -2);
        testNotDividedByZero(56331, -2);
        testNotDividedByZero(Js_int.min, -2);
        testNotDividedByZero(Js_int.max, -2);
        testNotDividedByZero(Js_int.min + 1 | 0, -2);
        testNotDividedByZero(Js_int.max - 1 | 0, -2);
        var testDividedByZero = function (i) {
          var a = fromIntExn(i);
          t.deepEqual($$Number.Int32.div(a, zero), undefined, undefined);
          TestUtils.assertDivisionByZero(t, (function () {
                  return $$Number.Int32.divExn(a, zero);
                }));
          var negZero$1 = fromIntExn(negZero);
          t.deepEqual($$Number.Int32.div(a, negZero$1), undefined, undefined);
          TestUtils.assertDivisionByZero(t, (function () {
                  return $$Number.Int32.divExn(a, negZero$1);
                }));
        };
        testFn(testDividedByZero);
        TestUtils.loop100Fn(function () {
              var a = TestUtils.randomInt(Js_int.min, Js_int.max);
              var b = TestUtils.randomInt(Js_int.min, Js_int.max);
              testNotDividedByZero(a, b);
              testDividedByZero(a);
              testDividedByZero(b);
            });
      }));

Ava("test " + name + " remainder", (function (t) {
        var testNotModByZero = function (a, b) {
          if (a !== 0) {
            var result = fromIntExn(Caml_int32.mod_(b, a) | 0);
            var a$1 = fromIntExn(a);
            var b$1 = fromIntExn(b);
            t.deepEqual($$Number.Int32.rem(b$1, a$1), Caml_option.some(result), undefined);
            t.deepEqual($$Number.Int32.remExn(b$1, a$1), result, undefined);
            t.deepEqual($$Number.Int32.remUnsafe(b$1, a$1), result, undefined);
            t.deepEqual($$Number.Int32.rem(zero, a$1), Caml_option.some(zero), undefined);
            t.deepEqual($$Number.Int32.remExn(zero, a$1), zero, undefined);
            t.deepEqual($$Number.Int32.remUnsafe(zero, a$1), zero, undefined);
          }
          if (b !== 0) {
            var result$1 = fromIntExn(Caml_int32.mod_(a, b) | 0);
            var a$2 = fromIntExn(a);
            var b$2 = fromIntExn(b);
            t.deepEqual($$Number.Int32.rem(a$2, b$2), Caml_option.some(result$1), undefined);
            t.deepEqual($$Number.Int32.remExn(a$2, b$2), result$1, undefined);
            t.deepEqual($$Number.Int32.remUnsafe(a$2, b$2), result$1, undefined);
            t.deepEqual($$Number.Int32.rem(zero, b$2), Caml_option.some(zero), undefined);
            t.deepEqual($$Number.Int32.remExn(zero, b$2), zero, undefined);
            t.deepEqual($$Number.Int32.remUnsafe(zero, b$2), zero, undefined);
          }
          var a$3 = fromIntExn(a);
          var b$3 = fromIntExn(b);
          t.deepEqual($$Number.Int32.rem(a$3, one), Caml_option.some(zero), undefined);
          t.deepEqual($$Number.Int32.remExn(a$3, one), zero, undefined);
          t.deepEqual($$Number.Int32.remUnsafe(a$3, one), zero, undefined);
          t.deepEqual($$Number.Int32.rem(b$3, one), Caml_option.some(zero), undefined);
          t.deepEqual($$Number.Int32.remExn(b$3, one), zero, undefined);
          t.deepEqual($$Number.Int32.remUnsafe(b$3, one), zero, undefined);
          var negOne = fromIntExn(-1);
          t.deepEqual($$Number.Int32.rem(a$3, negOne), Caml_option.some(zero), undefined);
          t.deepEqual($$Number.Int32.remExn(a$3, negOne), zero, undefined);
          t.deepEqual($$Number.Int32.remUnsafe(a$3, negOne), zero, undefined);
          t.deepEqual($$Number.Int32.rem(b$3, negOne), Caml_option.some(zero), undefined);
          t.deepEqual($$Number.Int32.remExn(b$3, negOne), zero, undefined);
          t.deepEqual($$Number.Int32.remUnsafe(b$3, negOne), zero, undefined);
        };
        testNotModByZero(-27852, 56331);
        testNotModByZero(Js_int.min, -27852);
        testNotModByZero(Js_int.min, 56331);
        testNotModByZero(Js_int.max, -27852);
        testNotModByZero(Js_int.max, 56331);
        testNotModByZero(-27852, 2);
        testNotModByZero(56331, 2);
        testNotModByZero(Js_int.min, 2);
        testNotModByZero(Js_int.max, 2);
        testNotModByZero(Js_int.min + 1 | 0, 2);
        testNotModByZero(Js_int.max - 1 | 0, 2);
        testNotModByZero(-27852, -56331);
        testNotModByZero(56331, 27852);
        testNotModByZero(27852, -56331);
        testNotModByZero(Js_int.min, 27852);
        testNotModByZero(Js_int.min, -56331);
        testNotModByZero(Js_int.max, 27852);
        testNotModByZero(Js_int.max, -56331);
        testNotModByZero(-Js_int.max | 0, 27852);
        testNotModByZero(-Js_int.max | 0, -56331);
        testNotModByZero(-27852, -2);
        testNotModByZero(56331, -2);
        testNotModByZero(Js_int.min, -2);
        testNotModByZero(Js_int.max, -2);
        testNotModByZero(Js_int.min + 1 | 0, -2);
        testNotModByZero(Js_int.max - 1 | 0, -2);
        var testModByZero = function (a) {
          var a$1 = fromIntExn(a);
          t.deepEqual($$Number.Int32.rem(a$1, zero), undefined, undefined);
          TestUtils.assertDivisionByZero(t, (function () {
                  return $$Number.Int32.remExn(a$1, zero);
                }));
          var negZero$1 = fromIntExn(negZero);
          t.deepEqual($$Number.Int32.rem(a$1, negZero$1), undefined, undefined);
          TestUtils.assertDivisionByZero(t, (function () {
                  return $$Number.Int32.remExn(a$1, negZero$1);
                }));
        };
        testFn(testModByZero);
        TestUtils.loop100Fn(function () {
              var a = TestUtils.randomInt(Js_int.min, Js_int.max);
              var b = TestUtils.randomInt(Js_int.min, Js_int.max);
              testNotModByZero(a, b);
              testModByZero(a);
              testModByZero(b);
            });
      }));

Ava("test " + name + " sum", (function (t) {
        var testInRange = function (arr) {
          var result = fromIntExn(Belt_Array.reduce(arr, 0, (function (acc, v) {
                      return acc + v | 0;
                    })));
          var arr$1 = Belt_Array.mapU(arr, (function (i) {
                  return fromIntExn(i);
                }));
          t.deepEqual($$Number.Int32.sum(arr$1), Caml_option.some(result), undefined);
          t.deepEqual($$Number.Int32.sumExn(arr$1), result, undefined);
          t.deepEqual($$Number.Int32.sumUnsafe(arr$1), result, undefined);
        };
        testInRange([-27852]);
        testInRange([56331]);
        testInRange([Js_int.min]);
        testInRange([Js_int.max]);
        testInRange([Js_int.min + 1 | 0]);
        testInRange([Js_int.max - 1 | 0]);
        testInRange([
              -27852,
              56331
            ]);
        testInRange([
              56331,
              -27852
            ]);
        testInRange([
              -27852,
              0,
              1000000000,
              1,
              56331
            ]);
        testInRange([
              Js_int.min,
              Js_int.max
            ]);
        t.deepEqual($$Number.Int32.sum([]), undefined, undefined);
        TestUtils.assertInvalidArgument(t, (function () {
                return $$Number.Int32.sumExn([]);
              }));
        var testOutOfRange = function (arr) {
          var arr$1 = Belt_Array.mapU(arr, (function (i) {
                  return fromIntExn(i);
                }));
          t.deepEqual($$Number.Int32.sum(arr$1), undefined, undefined);
          TestUtils.assertOverflow(t, (function () {
                  return $$Number.Int32.sumExn(arr$1);
                }));
        };
        testOutOfRange([
              Js_int.max,
              1
            ]);
        testOutOfRange([
              1,
              Js_int.max
            ]);
        testOutOfRange([
              Js_int.max,
              1000000000
            ]);
        testOutOfRange([
              1000000000,
              Js_int.max
            ]);
        testOutOfRange([
              Js_int.max,
              84183,
              1000000000
            ]);
        testOutOfRange([
              Js_int.min,
              -1
            ]);
        testOutOfRange([
              -1,
              Js_int.min
            ]);
        testOutOfRange([
              Js_int.min,
              -1000000000
            ]);
        testOutOfRange([
              -1000000000,
              Js_int.min
            ]);
        testOutOfRange([
              Js_int.min,
              -84183,
              -1000000000
            ]);
        TestUtils.loop100Fn(function () {
              var a = TestUtils.randomInt(Js_int.min, Js_int.max);
              var b = TestUtils.randomInt(Js_int.min, Js_int.max);
              testInRange([a]);
              testInRange([b]);
              var result = a + b;
              if (result >= Js_int.min && result <= Js_int.max) {
                testInRange([
                      a,
                      b
                    ]);
                return testInRange([
                            b,
                            a
                          ]);
              } else {
                testOutOfRange([
                      a,
                      b
                    ]);
                return testOutOfRange([
                            b,
                            a
                          ]);
              }
            });
      }));

Ava("test " + name + " increase and decrease", (function (t) {
        var testIncInRange = function (i) {
          var result = fromIntExn(i + 1 | 0);
          var n = fromIntExn(i);
          t.deepEqual($$Number.Int32.inc(n), Caml_option.some(result), undefined);
          t.deepEqual($$Number.Int32.incExn(n), result, undefined);
          t.deepEqual($$Number.Int32.incUnsafe(n), result, undefined);
        };
        testIncInRange(0);
        testIncInRange(1);
        testIncInRange(1000000000);
        testIncInRange(Js_int.min);
        testIncInRange(Js_int.min + 1 | 0);
        testIncInRange(Js_int.max - 1 | 0);
        TestUtils.loop100Fn(function () {
              testIncInRange(TestUtils.randomInt(Js_int.min, Js_int.max));
            });
        testIncInRange(-1000000000);
        testIncInRange(-Js_int.max | 0);
        t.deepEqual($$Number.Int32.inc($$Number.Int32.maxValue), undefined, undefined);
        TestUtils.assertOverflow(t, (function () {
                return $$Number.Int32.incExn($$Number.Int32.maxValue);
              }));
        var testDecInRange = function (i) {
          var result = fromIntExn(i - 1 | 0);
          var n = fromIntExn(i);
          t.deepEqual($$Number.Int32.dec(n), Caml_option.some(result), undefined);
          t.deepEqual($$Number.Int32.decExn(n), result, undefined);
          t.deepEqual($$Number.Int32.decUnsafe(n), result, undefined);
        };
        testDecInRange(1);
        testDecInRange(1000000000);
        testDecInRange(Js_int.min + 1 | 0);
        testDecInRange(Js_int.max);
        testDecInRange(Js_int.max - 1 | 0);
        TestUtils.loop100Fn(function () {
              testDecInRange(TestUtils.randomInt(Js_int.min + 1.0, Js_int.max));
            });
        testDecInRange(0);
        testDecInRange(-1000000000);
        testDecInRange(-Js_int.max | 0);
        t.deepEqual($$Number.Int32.dec($$Number.Int32.minValue), undefined, undefined);
        TestUtils.assertOverflow(t, (function () {
                return $$Number.Int32.decExn($$Number.Int32.minValue);
              }));
      }));

Ava("test " + name + " bitwise", (function (t) {
        var assertNot1 = function (a, b) {
          var a$1 = fromIntExn(a);
          var b$1 = fromIntExn(b);
          t.deepEqual($$Number.Int32.lnot(a$1), b$1, undefined);
          t.deepEqual($$Number.Int32.lnot(b$1), a$1, undefined);
        };
        assertNot1(1000000000, -1000000001);
        assertNot1(Js_int.min, Js_int.max);
        assertNot1(Js_int.min + 1 | 0, Js_int.max - 1 | 0);
        assertNot1(0, -1);
        var assertNot2 = function (i) {
          var n = fromIntExn(i);
          t.deepEqual($$Number.Int32.lnot($$Number.Int32.lnot(n)), n, undefined);
        };
        testFn(assertNot2);
        assertNot2(-1);
        assertNot2(-Js_int.max | 0);
        var assertAnd = function (a, b, value) {
          var a$1 = fromIntExn(a);
          var b$1 = fromIntExn(b);
          var value$1 = fromIntExn(value);
          t.deepEqual($$Number.Int32.land(a$1, a$1), a$1, undefined);
          t.deepEqual($$Number.Int32.land(b$1, b$1), b$1, undefined);
          t.deepEqual($$Number.Int32.land(value$1, value$1), value$1, undefined);
          t.deepEqual($$Number.Int32.land(a$1, $$Number.Int32.lnot(a$1)), zero, undefined);
          t.deepEqual($$Number.Int32.land(b$1, $$Number.Int32.lnot(b$1)), zero, undefined);
          t.deepEqual($$Number.Int32.land(value$1, $$Number.Int32.lnot(value$1)), zero, undefined);
          t.deepEqual($$Number.Int32.land(a$1, b$1), value$1, undefined);
          t.deepEqual($$Number.Int32.land(b$1, a$1), value$1, undefined);
        };
        assertAnd(1000000000, -1000000001, 0);
        assertAnd(Js_int.min, Js_int.max, 0);
        assertAnd(Js_int.min + 1 | 0, Js_int.max - 1 | 0, 0);
        assertAnd(-27852, 56331, 36864);
        TestUtils.loop100Fn(function () {
              var value = TestUtils.randomInt(Js_int.min, Js_int.max);
              assertAnd(value, value, value);
            });
        assertAnd(0, -1, 0);
        var assertOr = function (a, b, value) {
          var a$1 = fromIntExn(a);
          var b$1 = fromIntExn(b);
          var value$1 = fromIntExn(value);
          var oneBits = fromIntExn(-1);
          t.deepEqual($$Number.Int32.lor(a$1, a$1), a$1, undefined);
          t.deepEqual($$Number.Int32.lor(b$1, b$1), b$1, undefined);
          t.deepEqual($$Number.Int32.lor(value$1, value$1), value$1, undefined);
          t.deepEqual($$Number.Int32.lor(a$1, $$Number.Int32.lnot(a$1)), oneBits, undefined);
          t.deepEqual($$Number.Int32.lor(b$1, $$Number.Int32.lnot(b$1)), oneBits, undefined);
          t.deepEqual($$Number.Int32.lor(value$1, $$Number.Int32.lnot(value$1)), oneBits, undefined);
          t.deepEqual($$Number.Int32.lor(a$1, b$1), value$1, undefined);
          t.deepEqual($$Number.Int32.lor(b$1, a$1), value$1, undefined);
        };
        assertOr(-27852, 56331, -8385);
        TestUtils.loop100Fn(function () {
              var value = TestUtils.randomInt(Js_int.min, Js_int.max);
              assertOr(value, value, value);
            });
        assertOr(1000000000, -1000000001, -1);
        assertOr(Js_int.min, Js_int.max, -1);
        assertOr(Js_int.min + 1 | 0, Js_int.max - 1 | 0, -1);
        assertOr(0, -1, -1);
        var assertXor = function (a, b, value) {
          var a$1 = fromIntExn(a);
          var b$1 = fromIntExn(b);
          var value$1 = fromIntExn(value);
          var oneBits = fromIntExn(-1);
          t.deepEqual($$Number.Int32.lxor(a$1, a$1), zero, undefined);
          t.deepEqual($$Number.Int32.lxor(b$1, b$1), zero, undefined);
          t.deepEqual($$Number.Int32.lxor(value$1, value$1), zero, undefined);
          t.deepEqual($$Number.Int32.lxor(a$1, $$Number.Int32.lnot(a$1)), oneBits, undefined);
          t.deepEqual($$Number.Int32.lxor(b$1, $$Number.Int32.lnot(b$1)), oneBits, undefined);
          t.deepEqual($$Number.Int32.lxor(value$1, $$Number.Int32.lnot(value$1)), oneBits, undefined);
          t.deepEqual($$Number.Int32.lxor(a$1, b$1), value$1, undefined);
          t.deepEqual($$Number.Int32.lxor(b$1, a$1), value$1, undefined);
        };
        assertXor(-27852, 56331, -45249);
        TestUtils.loop100Fn(function () {
              var value = TestUtils.randomInt(Js_int.min, Js_int.max);
              assertXor(value, value, 0);
            });
        assertXor(1000000000, -1000000001, -1);
        assertXor(Js_int.min, Js_int.max, -1);
        assertXor(Js_int.min + 1 | 0, Js_int.max - 1 | 0, -1);
        assertXor(0, -1, -1);
        var modBits = function (i) {
          return ((i >>> 0) % bits);
        };
        var value = fromIntExn(1000000000);
        for(var i = -32; i <= 64; ++i){
          t.deepEqual($$Number.Int32.lsl(value, i), fromIntExn(Belt_Array.getExn(valueShiftLeft, modBits(i))), undefined);
        }
        var testUnsignedShiftRight = function (value) {
          var n = fromIntExn(value);
          for(var i = -32; i <= 64; ++i){
            t.deepEqual($$Number.Int32.lsr(n, i), fromIntExn((value >>> i) | 0), undefined);
          }
        };
        testUnsignedShiftRight(1000000000);
        testUnsignedShiftRight(-1000000001);
        TestUtils.loop100Fn(function () {
              testUnsignedShiftRight(TestUtils.randomInt(Js_int.min, Js_int.max));
            });
        var testShiftRight = function (value) {
          var n = fromIntExn(value);
          for(var i = -32; i <= 64; ++i){
            t.deepEqual($$Number.Int32.asr(n, i), fromFloatExn(Math.floor(value / Math.pow(2.0, modBits(i)))), undefined);
            t.deepEqual($$Number.Int32.lnot($$Number.Int32.asr(n, i)), $$Number.Int32.asr($$Number.Int32.lnot(n), i), undefined);
          }
        };
        testShiftRight(1000000000);
        testShiftRight(-1000000001);
        TestUtils.loop100Fn(function () {
              testShiftRight(TestUtils.randomInt(Js_int.min, Js_int.max));
            });
        var value$1 = fromIntExn(1000000000);
        for(var i$1 = -32; i$1 <= 64; ++i$1){
          t.deepEqual($$Number.Int32.rsl(value$1, i$1), fromIntExn(Belt_Array.getExn(valueRotateShiftLeft, modBits(i$1))), undefined);
        }
        var testRotateShiftLeft = function (value) {
          var n = fromIntExn(value);
          for(var i = -32; i <= 64; ++i){
            t.deepEqual($$Number.Int32.lnot($$Number.Int32.rsl(n, i)), $$Number.Int32.rsl($$Number.Int32.lnot(n), i), undefined);
          }
        };
        testRotateShiftLeft(1000000000);
        testRotateShiftLeft(-1000000001);
        TestUtils.loop100Fn(function () {
              testRotateShiftLeft(TestUtils.randomInt(Js_int.min, Js_int.max));
            });
        var testRotateShiftRight = function (value) {
          var n = fromIntExn(value);
          for(var i = -32; i <= 64; ++i){
            t.deepEqual($$Number.Int32.rsl(n, i), $$Number.Int32.rsr(n, 32 - i | 0), undefined);
            t.deepEqual($$Number.Int32.lnot($$Number.Int32.rsr(n, i)), $$Number.Int32.rsr($$Number.Int32.lnot(n), i), undefined);
          }
        };
        testRotateShiftRight(1000000000);
        testRotateShiftRight(-1000000001);
        TestUtils.loop100Fn(function () {
              testRotateShiftRight(TestUtils.randomInt(Js_int.min, Js_int.max));
            });
      }));

Ava("test " + name + " integer math", (function (t) {
        var testClz = function (n, result) {
          t.deepEqual($$Number.Int32.clz(n), result, undefined);
        };
        testClz(zero, 32);
        testClz(fromIntExn(-1), 0);
        testClz($$Number.Int32.minValue, 0);
        testClz($$Number.Int32.maxValue, 1);
        for(var i = 0; i <= 31; ++i){
          testClz($$Number.Int32.lsl(one, i), (32 - i | 0) - 1 | 0);
        }
        t.deepEqual($$Number.Int32.imul(fromIntExn(-27852), fromIntExn(56331)), fromIntExn(-1568931012), undefined);
        var mask = -1;
        var j = Math.pow(2.0, 32);
        var k = Math.pow(2.0, 31);
        var toU32 = function (i) {
          return TestUtils.intToUint32(i & mask);
        };
        TestUtils.loop100Fn(function () {
              var a = TestUtils.randomInt(0.0, 1000000.0);
              var b = TestUtils.randomInt(Js_int.min, 1000000.0);
              var m = toU32(a) * toU32(b) % j;
              var result = true && m >= k ? m - j : m;
              t.deepEqual($$Number.Int32.imul(fromIntExn(a), fromIntExn(b)), fromFloatExn(result), undefined);
              t.deepEqual($$Number.Int32.imul(fromIntExn(b), fromIntExn(a)), fromFloatExn(result), undefined);
            });
        TestUtils.loop100Fn(function () {
              var a = TestUtils.randomInt(Js_int.min, Js_int.max);
              var b = TestUtils.randomInt(Js_int.min, Js_int.max);
              t.deepEqual($$Number.Int32.imul(fromIntExn(a), fromIntExn(b)), fromIntExn(Math.imul(a, b)), undefined);
              t.deepEqual($$Number.Int32.imul(fromIntExn(a), fromIntExn(b)), $$Number.Int32.imul(fromIntExn(b), fromIntExn(a)), undefined);
            });
        var testPowInRange = function (a, b) {
          var result = fromFloatExn(Math.pow(a, b));
          var a$1 = fromIntExn(a);
          var b$1 = fromIntExn(b);
          t.deepEqual($$Number.Int32.pow(a$1, b$1), Caml_option.some(result), undefined);
          t.deepEqual($$Number.Int32.powExn(a$1, b$1), result, undefined);
          t.deepEqual($$Number.Int32.powUnsafe(a$1, b$1), result, undefined);
          t.deepEqual($$Number.Int32.pow(a$1, zero), Caml_option.some(one), undefined);
          t.deepEqual($$Number.Int32.powExn(a$1, zero), one, undefined);
          t.deepEqual($$Number.Int32.powUnsafe(a$1, zero), one, undefined);
          t.deepEqual($$Number.Int32.pow(b$1, zero), Caml_option.some(one), undefined);
          t.deepEqual($$Number.Int32.powExn(b$1, zero), one, undefined);
          t.deepEqual($$Number.Int32.powUnsafe(b$1, zero), one, undefined);
          t.deepEqual($$Number.Int32.pow(a$1, one), Caml_option.some(a$1), undefined);
          t.deepEqual($$Number.Int32.powExn(a$1, one), a$1, undefined);
          t.deepEqual($$Number.Int32.powUnsafe(a$1, one), a$1, undefined);
          t.deepEqual($$Number.Int32.pow(b$1, one), Caml_option.some(b$1), undefined);
          t.deepEqual($$Number.Int32.powExn(b$1, one), b$1, undefined);
          t.deepEqual($$Number.Int32.powUnsafe(b$1, one), b$1, undefined);
        };
        testPowInRange(0, 1);
        testPowInRange(1, 0);
        testPowInRange(1000000000, 0);
        testPowInRange(Js_int.min, 1);
        testPowInRange(Js_int.max, 1);
        var testPowOutOfRange = function (a, b) {
          var a$1 = fromIntExn(a);
          var b$1 = fromIntExn(b);
          t.deepEqual($$Number.Int32.pow(a$1, b$1), undefined, undefined);
          TestUtils.assertOverflow(t, (function () {
                  return $$Number.Int32.powExn(a$1, b$1);
                }));
        };
        testPowOutOfRange(Js_int.max, 2);
        testPowOutOfRange(Js_int.min, 2);
        TestUtils.loop100Fn(function () {
              var a = TestUtils.randomInt(Js_int.min, Js_int.max);
              var b = TestUtils.randomPositiveSmallInt(undefined);
              var result = Math.pow(a, b);
              if (result >= Js_int.min && result <= Js_int.max) {
                return testPowInRange(a, b);
              } else {
                return testPowOutOfRange(a, b);
              }
            });
        var testPowNotInteger = function (a, b) {
          var a$1 = fromIntExn(a);
          var b$1 = fromIntExn(b);
          t.deepEqual($$Number.Int32.pow(a$1, b$1), undefined, undefined);
          TestUtils.assertInvalidArgument(t, (function () {
                  return $$Number.Int32.powExn(a$1, b$1);
                }));
        };
        testPowNotInteger(1000000000, -1);
        testPowNotInteger(Js_int.min, -1);
        testPowNotInteger(Js_int.max, -1);
        TestUtils.loop100Fn(function () {
              var m = TestUtils.randomInt(Js_int.min, Js_int.max);
              var n = TestUtils.randomInt(Js_int.min, Js_int.max);
              var min = fromIntExn(m < n ? m : n);
              var max = fromIntExn(m > n ? m : n);
              if (min !== max) {
                return TestUtils.loopFn((function () {
                              var i = $$Number.Int32.random(min, max);
                              t.true($$Number.Int32.ge(i, min), undefined);
                              t.true($$Number.Int32.lt(i, max), undefined);
                            }), 10);
              }
              
            });
      }));

Ava("test " + name + " signed math", (function (t) {
        var testNegInRange = function (i) {
          var a = fromIntExn(i);
          var b = fromIntExn(-i | 0);
          t.deepEqual($$Number.Int32.neg(a), Caml_option.some(b), undefined);
          t.deepEqual($$Number.Int32.negExn(a), b, undefined);
          t.deepEqual($$Number.Int32.negUnsafe(a), b, undefined);
          t.deepEqual($$Number.Int32.neg(b), Caml_option.some(a), undefined);
          t.deepEqual($$Number.Int32.negExn(b), a, undefined);
          t.deepEqual($$Number.Int32.negUnsafe(b), a, undefined);
        };
        testNegInRange(0);
        testNegInRange(negZero);
        testNegInRange(1);
        testNegInRange(1000000000);
        testNegInRange(Js_int.min + 1 | 0);
        testNegInRange(Js_int.max);
        testNegInRange(Js_int.max - 1 | 0);
        var testNegOutOfRange = function (i) {
          var n = fromIntExn(i);
          t.deepEqual($$Number.Int32.neg(n), undefined, undefined);
          TestUtils.assertOverflow(t, (function () {
                  return $$Number.Int32.negExn(n);
                }));
        };
        testNegOutOfRange(Js_int.min);
        TestUtils.loop100Fn(function () {
              var i = TestUtils.randomInt(Js_int.min, Js_int.max);
              if (i !== Js_int.min) {
                return testNegInRange(i);
              } else {
                return testNegOutOfRange(i);
              }
            });
        var testAbsInRange = function (i) {
          var a = fromIntExn(i);
          var b = fromIntExn(i < 0 ? -i | 0 : i);
          t.deepEqual($$Number.Int32.abs(a), Caml_option.some(b), undefined);
          t.deepEqual($$Number.Int32.absExn(a), b, undefined);
          t.deepEqual($$Number.Int32.absUnsafe(a), b, undefined);
          t.deepEqual($$Number.Int32.abs(b), Caml_option.some(b), undefined);
          t.deepEqual($$Number.Int32.absExn(b), b, undefined);
          t.deepEqual($$Number.Int32.absUnsafe(b), b, undefined);
        };
        testAbsInRange(0);
        testAbsInRange(negZero);
        testAbsInRange(-1);
        testAbsInRange(-1000000000);
        testAbsInRange(-Js_int.max | 0);
        testAbsInRange((-Js_int.max | 0) + 1 | 0);
        var testAbsOutOfRange = function (i) {
          var n = fromIntExn(i);
          t.deepEqual($$Number.Int32.abs(n), undefined, undefined);
          TestUtils.assertOverflow(t, (function () {
                  return $$Number.Int32.absExn(n);
                }));
        };
        testAbsOutOfRange(Js_int.min);
        TestUtils.loop100Fn(function () {
              var i = TestUtils.randomInt(Js_int.min, Js_int.max);
              if (i !== Js_int.min) {
                return testAbsInRange(i);
              } else {
                return testAbsOutOfRange(i);
              }
            });
        var testSign = function (i) {
          var test_ = function (i) {
            var n = fromIntExn(i);
            var result = i < 0 ? -1 : (
                i > 0 ? 1 : 0
              );
            var raw = i < 0 ? -1.0 : (
                i > 0 ? 1.0 : 0.0
              );
            t.deepEqual($$Number.Int32.sign(n), result, undefined);
            t.deepEqual($$Number.Int32.signExn(n), result, undefined);
            t.deepEqual($$Number.Int32.signRaw(n), raw, undefined);
          };
          test_(i);
          if (i !== Js_int.min) {
            return test_(-i | 0);
          }
          
        };
        testFn(testSign);
      }));

var IntModule;

var isSigned = true;

var is32Bits = true;

var bits = 32;

var minValue = Js_int.min;

var maxValue = Js_int.max;

var value = 1000000000;

var valueNot = -1000000001;

var less = -27852;

var greater = 56331;

var lessGreaterAnd = 36864;

var lessGreaterOr = -8385;

var lessGreaterXor = -45249;

export {
  IntModule ,
  name ,
  isSigned ,
  is32Bits ,
  bits ,
  minValue ,
  maxValue ,
  value ,
  valueNot ,
  valueShiftLeft ,
  valueRotateShiftLeft ,
  less ,
  greater ,
  lessGreaterAnd ,
  lessGreaterOr ,
  lessGreaterXor ,
  negZero ,
  zero ,
  one ,
  fromIntExn ,
  fromFloatExn ,
  randomValue ,
  randomLargerInt ,
  randomSmallerInt ,
  testFn ,
}
/*  Not a pure module */
