// Generated by ReScript, PLEASE EDIT WITH CARE

import Ava from "ava";
import * as Js_int from "rescript/lib/es6/js_int.js";
import * as $$Number from "../src/Number.res.mjs";
import * as TestUtils from "./TestUtils.res.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as PervasivesU from "rescript/lib/es6/pervasivesU.js";

var name = "Uint8";

var valueShiftLeft = [
  150,
  44,
  88,
  176,
  96,
  192,
  128,
  0
];

var valueRotateShiftLeft = [
  150,
  45,
  90,
  180,
  105,
  210,
  165,
  75
];

var negZero = -0;

var zero = $$Number.Uint8.zero;

var one = $$Number.Uint8.one;

var fromIntExn = $$Number.Uint8.fromIntExn;

var fromFloatExn = $$Number.Uint8.fromFloatExn;

function randomValue() {
  return TestUtils.randomInt(0, 255);
}

function randomLargerInt() {
  return TestUtils.randomInt(255 + 1.0, Js_int.max);
}

function randomSmallerInt() {
  return TestUtils.randomInt(Js_int.min, 0);
}

function testFn(fn) {
  fn(0);
  fn(negZero);
  fn(1);
  fn(150);
  fn(7);
  fn(27);
  fn(0);
  fn(1);
  fn(255);
  fn(254);
  TestUtils.loop100Fn(function () {
        fn(TestUtils.randomInt(0, 255));
      });
}

Ava("test " + name + " sign", (function (t) {
        t.deepEqual($$Number.Uint8.isSigned, false, undefined);
        t.deepEqual($$Number.Uint8.isUnsigned, true, undefined);
      }));

Ava("test " + name + " bits", (function (t) {
        t.deepEqual($$Number.Uint8.bits, 8, undefined);
      }));

Ava("test " + name + " from int", (function (t) {
        var testInRange = function (i) {
          var n = fromIntExn(i);
          t.deepEqual($$Number.Uint8.fromInt(i), Caml_option.some(n), undefined);
          t.deepEqual(fromIntExn(i), n, undefined);
          t.deepEqual($$Number.Uint8.fromIntClamped(i), n, undefined);
          t.deepEqual($$Number.Uint8.fromIntUnsafe(i), n, undefined);
        };
        testFn(testInRange);
        var testOutOfRange = function (i, value) {
          t.deepEqual($$Number.Uint8.fromInt(i), undefined, undefined);
          TestUtils.assertOverflow(t, (function () {
                  return fromIntExn(i);
                }));
          t.deepEqual($$Number.Uint8.fromIntClamped(i), fromIntExn(value), undefined);
        };
        testOutOfRange(-1, 0);
        testOutOfRange(256, 255);
        testOutOfRange(-150, 0);
        testOutOfRange(405, 255);
        TestUtils.loop100Fn(function () {
              testOutOfRange(randomLargerInt(), 255);
            });
        TestUtils.loop100Fn(function () {
              testOutOfRange(TestUtils.randomInt(Js_int.min, 0), 0);
            });
      }));

Ava("test " + name + " to int", (function (t) {
        var testToInt = function (i) {
          var n = fromIntExn(i);
          var i$1 = i | 0;
          t.deepEqual($$Number.Uint8.toInt(n), i$1, undefined);
          t.deepEqual($$Number.Uint8.toIntExn(n), i$1, undefined);
          t.deepEqual($$Number.Uint8.toIntClamped(n), i$1, undefined);
          t.deepEqual($$Number.Uint8.toIntUnsafe(n), i$1, undefined);
        };
        testFn(testToInt);
      }));

Ava("test " + name + " from float", (function (t) {
        var testIsIntegerAndInRange = function (i) {
          var n = fromIntExn(i);
          t.deepEqual($$Number.Uint8.fromFloat(i), Caml_option.some(n), undefined);
          t.deepEqual(fromFloatExn(i), n, undefined);
          t.deepEqual($$Number.Uint8.fromFloatClamped(i), n, undefined);
          t.deepEqual($$Number.Uint8.fromFloatUnsafe(i), n, undefined);
        };
        testFn(testIsIntegerAndInRange);
        var testOutOfRange = function (f, value) {
          t.deepEqual($$Number.Uint8.fromFloat(f), undefined, undefined);
          TestUtils.assertOverflow(t, (function () {
                  return fromFloatExn(f);
                }));
          t.deepEqual($$Number.Uint8.fromFloatClamped(f), fromIntExn(value), undefined);
        };
        testOutOfRange(-1.0, 0);
        testOutOfRange(255 + 1.0, 255);
        testOutOfRange(-150, 0);
        testOutOfRange(405, 255);
        TestUtils.loop100Fn(function () {
              testOutOfRange(Math.floor(TestUtils.randomFloat(255 + 1.0, TestUtils.maxSafeInteger)), 255);
            });
        TestUtils.loop100Fn(function () {
              testOutOfRange(Math.floor(TestUtils.randomFloat(TestUtils.minSafeInteger, -1.0)), 0);
            });
        var testIsNotInteger = function (f, value) {
          t.deepEqual($$Number.Uint8.fromFloat(f), undefined, undefined);
          TestUtils.assertInvalidArgument(t, (function () {
                  return fromFloatExn(f);
                }));
          t.deepEqual($$Number.Uint8.fromFloatClamped(f), fromIntExn(value), undefined);
        };
        testIsNotInteger(150 + 0.5, 150);
        testIsNotInteger(0 + 0.1, 0);
        testIsNotInteger(Number.NaN, 0);
        testIsNotInteger(PervasivesU.neg_infinity, 0);
        testIsNotInteger(PervasivesU.infinity, 255);
        testIsNotInteger(-0.1, 0);
        testIsNotInteger(255 + 0.1, 255);
        testIsNotInteger(255 - 0.1, 254);
        testIsNotInteger(-150 - 0.5, 0);
        testIsNotInteger(405 + 0.5, 255);
      }));

Ava("test " + name + " to float", (function (t) {
        var testToFloat = function (i) {
          t.deepEqual($$Number.Uint8.toFloat(fromFloatExn(i)), i, undefined);
        };
        testToFloat(150);
        TestUtils.loop100Fn(function () {
              testToFloat(TestUtils.randomInt(0, 255));
            });
      }));

Ava("test " + name + " from string", (function (t) {
        var testInRange = function (i, s) {
          var n = fromIntExn(i);
          t.deepEqual($$Number.Uint8.fromString(s), Caml_option.some(n), undefined);
          t.deepEqual($$Number.Uint8.fromStringExn(s), n, undefined);
          for(var radix = 2; radix <= 36; ++radix){
            var s$1 = i.toString(radix);
            t.deepEqual($$Number.Uint8.fromStringWithRadix(s$1, radix), Caml_option.some(n), undefined);
            t.deepEqual($$Number.Uint8.fromStringWithRadixExn(s$1, radix), n, undefined);
          }
          TestUtils.assertInvalidArgument(t, (function () {
                  return $$Number.Uint8.fromStringWithRadixExn(s, 1);
                }));
          TestUtils.assertInvalidArgument(t, (function () {
                  return $$Number.Uint8.fromStringWithRadixExn(s, 37);
                }));
        };
        testInRange(0, "0");
        testInRange(0, "-0");
        testInRange(1, "1");
        testInRange(150, String(150));
        testInRange(150, String(150 + 0.5));
        testInRange(0, String(0));
        testInRange(255, String(255));
        testInRange(1, String(1));
        testInRange(254, String(254));
        TestUtils.loop100Fn(function () {
              var value = TestUtils.randomInt(0, 255);
              testInRange(value, String(value));
            });
        var testOutOfRange = function (f) {
          var s = String(f);
          t.deepEqual($$Number.Uint8.fromString(s), undefined, undefined);
          TestUtils.assertOverflow(t, (function () {
                  return $$Number.Uint8.fromStringExn(s);
                }));
          for(var radix = 2; radix <= 36; ++radix){
            var s$1 = f.toString(radix);
            t.deepEqual($$Number.Uint8.fromStringWithRadix(s$1, radix), undefined, undefined);
            TestUtils.assertOverflow(t, (function(radix,s$1){
                return function () {
                  return $$Number.Uint8.fromStringWithRadixExn(s$1, radix);
                }
                }(radix,s$1)));
          }
          TestUtils.assertInvalidArgument(t, (function () {
                  return $$Number.Uint8.fromStringWithRadixExn(s, 1);
                }));
          TestUtils.assertInvalidArgument(t, (function () {
                  return $$Number.Uint8.fromStringWithRadixExn(s, 37);
                }));
        };
        testOutOfRange(-1.0);
        testOutOfRange(255 + 1.0);
        testOutOfRange(-150);
        testOutOfRange(405);
        TestUtils.loop100Fn(function () {
              testOutOfRange(randomLargerInt());
            });
        TestUtils.loop100Fn(function () {
              testOutOfRange(TestUtils.randomInt(Js_int.min, 0));
            });
        var testIsNotInteger = function (s) {
          t.deepEqual($$Number.Uint8.fromString(s), undefined, undefined);
          TestUtils.assertInvalidArgument(t, (function () {
                  return $$Number.Uint8.fromStringExn(s);
                }));
          for(var radix = 2; radix <= 10; ++radix){
            t.deepEqual($$Number.Uint8.fromStringWithRadix(s, radix), undefined, undefined);
            TestUtils.assertInvalidArgument(t, (function(radix){
                return function () {
                  return $$Number.Uint8.fromStringWithRadixExn(s, radix);
                }
                }(radix)));
          }
          TestUtils.assertInvalidArgument(t, (function () {
                  return $$Number.Uint8.fromStringWithRadixExn(s, 1);
                }));
          TestUtils.assertInvalidArgument(t, (function () {
                  return $$Number.Uint8.fromStringWithRadixExn(s, 37);
                }));
        };
        testIsNotInteger("NaN");
        testIsNotInteger("Infinity");
        testIsNotInteger("-Infinity");
        testIsNotInteger("foo");
        testIsNotInteger("b1");
      }));

Ava("test " + name + " to string", (function (t) {
        var testToString = function (i) {
          var s = String(i);
          var n = fromIntExn(i);
          t.deepEqual($$Number.Uint8.toString(n), s, undefined);
          for(var radix = 2; radix <= 36; ++radix){
            var s$1 = i.toString(radix);
            t.deepEqual($$Number.Uint8.toStringWithRadixExn(n, radix), s$1, undefined);
          }
          t.throws((function () {
                  return $$Number.Uint8.toStringWithRadixExn(n, 1);
                }), undefined, undefined);
          t.throws((function () {
                  return $$Number.Uint8.toStringWithRadixExn(n, 37);
                }), undefined, undefined);
        };
        testFn(testToString);
        var testToExponential = function (i) {
          var s = i.toExponential();
          var n = fromIntExn(i);
          t.deepEqual($$Number.Uint8.toExponential(n), s, undefined);
          for(var digits = 0; digits <= 100; ++digits){
            var s$1 = i.toExponential(digits);
            t.deepEqual($$Number.Uint8.toExponentialWithPrecisionExn(n, digits), s$1, undefined);
          }
          t.throws((function () {
                  return $$Number.Uint8.toExponentialWithPrecisionExn(n, -1);
                }), undefined, undefined);
          t.throws((function () {
                  return $$Number.Uint8.toExponentialWithPrecisionExn(n, 101);
                }), undefined, undefined);
        };
        testFn(testToExponential);
        var testToPrecision = function (i) {
          var s = i.toPrecision();
          var n = fromIntExn(i);
          t.deepEqual($$Number.Uint8.toPrecision(n), s, undefined);
          for(var digits = 1; digits <= 100; ++digits){
            var s$1 = i.toPrecision(digits);
            t.deepEqual($$Number.Uint8.toPrecisionWithPrecisionExn(n, digits), s$1, undefined);
          }
          t.throws((function () {
                  return $$Number.Uint8.toPrecisionWithPrecisionExn(n, 0);
                }), undefined, undefined);
          t.throws((function () {
                  return $$Number.Uint8.toPrecisionWithPrecisionExn(n, 101);
                }), undefined, undefined);
        };
        testFn(testToPrecision);
      }));

Ava("test " + name + " zero", (function (t) {
        t.deepEqual(zero, fromIntExn(0), undefined);
        t.deepEqual(zero, fromFloatExn(0.0), undefined);
        t.deepEqual(zero, fromFloatExn(-0.0), undefined);
      }));

Ava("test " + name + " one", (function (t) {
        t.deepEqual(one, fromIntExn(1), undefined);
        t.deepEqual(one, fromFloatExn(1.0), undefined);
      }));

Ava("test " + name + " range", (function (t) {
        t.deepEqual($$Number.Uint8.minValue, fromIntExn(0), undefined);
        t.deepEqual($$Number.Uint8.minValue, fromFloatExn(0), undefined);
        t.deepEqual($$Number.Uint8.maxValue, fromIntExn(255), undefined);
        t.deepEqual($$Number.Uint8.maxValue, fromFloatExn(255), undefined);
      }));

Ava("test " + name + " comparison", (function (t) {
        var testCompare = function (less, greater) {
          var less$1 = fromIntExn(less);
          var greater$1 = fromIntExn(greater);
          var value = fromIntExn(150);
          var minValue = fromIntExn(0);
          var maxValue = fromIntExn(255);
          t.deepEqual($$Number.Uint8.compare(less$1, greater$1), -1, undefined);
          t.deepEqual($$Number.Uint8.compare(greater$1, less$1), 1, undefined);
          t.deepEqual($$Number.Uint8.compare(less$1, less$1), 0, undefined);
          t.deepEqual($$Number.Uint8.compare(greater$1, greater$1), 0, undefined);
          t.deepEqual($$Number.Uint8.compareExn(less$1, greater$1), -1, undefined);
          t.deepEqual($$Number.Uint8.compareExn(greater$1, less$1), 1, undefined);
          t.deepEqual($$Number.Uint8.compareExn(less$1, less$1), 0, undefined);
          t.deepEqual($$Number.Uint8.compareExn(greater$1, greater$1), 0, undefined);
          t.true($$Number.Uint8.eq(less$1, less$1), undefined);
          t.true($$Number.Uint8.eq(greater$1, greater$1), undefined);
          t.false($$Number.Uint8.eq(less$1, greater$1), undefined);
          t.false($$Number.Uint8.eq(greater$1, less$1), undefined);
          t.true($$Number.Uint8.ne(less$1, greater$1), undefined);
          t.true($$Number.Uint8.ne(greater$1, less$1), undefined);
          t.false($$Number.Uint8.ne(less$1, less$1), undefined);
          t.false($$Number.Uint8.ne(greater$1, greater$1), undefined);
          t.true($$Number.Uint8.lt(less$1, greater$1), undefined);
          t.false($$Number.Uint8.lt(greater$1, less$1), undefined);
          t.false($$Number.Uint8.lt(less$1, less$1), undefined);
          t.false($$Number.Uint8.lt(greater$1, greater$1), undefined);
          t.true($$Number.Uint8.le(less$1, greater$1), undefined);
          t.false($$Number.Uint8.le(greater$1, less$1), undefined);
          t.true($$Number.Uint8.le(less$1, less$1), undefined);
          t.true($$Number.Uint8.le(greater$1, greater$1), undefined);
          t.true($$Number.Uint8.gt(greater$1, less$1), undefined);
          t.false($$Number.Uint8.gt(less$1, greater$1), undefined);
          t.false($$Number.Uint8.gt(less$1, less$1), undefined);
          t.false($$Number.Uint8.gt(greater$1, greater$1), undefined);
          t.true($$Number.Uint8.ge(greater$1, less$1), undefined);
          t.false($$Number.Uint8.ge(less$1, greater$1), undefined);
          t.true($$Number.Uint8.ge(less$1, less$1), undefined);
          t.true($$Number.Uint8.ge(greater$1, greater$1), undefined);
          t.deepEqual($$Number.Uint8.min(less$1, greater$1), less$1, undefined);
          t.deepEqual($$Number.Uint8.min(greater$1, less$1), less$1, undefined);
          t.deepEqual($$Number.Uint8.min(less$1, less$1), less$1, undefined);
          t.deepEqual($$Number.Uint8.min(greater$1, greater$1), greater$1, undefined);
          t.deepEqual($$Number.Uint8.minMany([less$1]), Caml_option.some(less$1), undefined);
          t.deepEqual($$Number.Uint8.minMany([
                    less$1,
                    greater$1
                  ]), Caml_option.some(less$1), undefined);
          t.deepEqual($$Number.Uint8.minMany([
                    greater$1,
                    less$1
                  ]), Caml_option.some(less$1), undefined);
          t.deepEqual($$Number.Uint8.minMany([
                    less$1,
                    value,
                    greater$1,
                    minValue,
                    maxValue
                  ]), Caml_option.some(minValue), undefined);
          t.deepEqual($$Number.Uint8.minManyExn([less$1]), less$1, undefined);
          t.deepEqual($$Number.Uint8.minManyExn([
                    less$1,
                    greater$1
                  ]), less$1, undefined);
          t.deepEqual($$Number.Uint8.minManyExn([
                    greater$1,
                    less$1
                  ]), less$1, undefined);
          t.deepEqual($$Number.Uint8.minManyExn([
                    minValue,
                    maxValue,
                    less$1,
                    value,
                    greater$1
                  ]), minValue, undefined);
          t.deepEqual($$Number.Uint8.minManyUnsafe([less$1]), less$1, undefined);
          t.deepEqual($$Number.Uint8.minManyUnsafe([
                    less$1,
                    greater$1
                  ]), less$1, undefined);
          t.deepEqual($$Number.Uint8.minManyUnsafe([
                    greater$1,
                    less$1
                  ]), less$1, undefined);
          t.deepEqual($$Number.Uint8.minManyUnsafe([
                    less$1,
                    minValue,
                    maxValue,
                    value,
                    greater$1
                  ]), minValue, undefined);
          t.deepEqual($$Number.Uint8.max(less$1, greater$1), greater$1, undefined);
          t.deepEqual($$Number.Uint8.max(greater$1, less$1), greater$1, undefined);
          t.deepEqual($$Number.Uint8.max(less$1, less$1), less$1, undefined);
          t.deepEqual($$Number.Uint8.max(greater$1, greater$1), greater$1, undefined);
          t.deepEqual($$Number.Uint8.maxMany([less$1]), Caml_option.some(less$1), undefined);
          t.deepEqual($$Number.Uint8.maxMany([
                    less$1,
                    greater$1
                  ]), Caml_option.some(greater$1), undefined);
          t.deepEqual($$Number.Uint8.maxMany([
                    greater$1,
                    less$1
                  ]), Caml_option.some(greater$1), undefined);
          t.deepEqual($$Number.Uint8.maxMany([
                    less$1,
                    value,
                    greater$1,
                    minValue,
                    maxValue
                  ]), Caml_option.some(maxValue), undefined);
          t.deepEqual($$Number.Uint8.maxManyExn([less$1]), less$1, undefined);
          t.deepEqual($$Number.Uint8.maxManyExn([
                    less$1,
                    greater$1
                  ]), greater$1, undefined);
          t.deepEqual($$Number.Uint8.maxManyExn([
                    greater$1,
                    less$1
                  ]), greater$1, undefined);
          t.deepEqual($$Number.Uint8.maxManyExn([
                    minValue,
                    maxValue,
                    less$1,
                    value,
                    greater$1
                  ]), maxValue, undefined);
          t.deepEqual($$Number.Uint8.maxManyUnsafe([less$1]), less$1, undefined);
          t.deepEqual($$Number.Uint8.maxManyUnsafe([
                    less$1,
                    greater$1
                  ]), greater$1, undefined);
          t.deepEqual($$Number.Uint8.maxManyUnsafe([
                    greater$1,
                    less$1
                  ]), greater$1, undefined);
          t.deepEqual($$Number.Uint8.maxManyUnsafe([
                    less$1,
                    minValue,
                    maxValue,
                    value,
                    greater$1
                  ]), maxValue, undefined);
        };
        testCompare(7, 27);
        TestUtils.loop100Fn(function () {
              var less = TestUtils.randomInt(0, 255);
              var greater = TestUtils.randomInt(less + 1.0, 255 + 1.0);
              testCompare(less, greater);
            });
        var zero = fromIntExn(0);
        var negZero$1 = fromIntExn(negZero);
        t.true($$Number.Uint8.eq(zero, negZero$1), undefined);
        t.true($$Number.Uint8.le(zero, negZero$1), undefined);
        t.true($$Number.Uint8.ge(zero, negZero$1), undefined);
        t.false($$Number.Uint8.lt(zero, negZero$1), undefined);
        t.false($$Number.Uint8.gt(zero, negZero$1), undefined);
        t.deepEqual($$Number.Uint8.minMany([]), undefined, undefined);
        TestUtils.assertInvalidArgument(t, (function () {
                return $$Number.Uint8.minManyExn([]);
              }));
        t.deepEqual($$Number.Uint8.maxMany([]), undefined, undefined);
        TestUtils.assertInvalidArgument(t, (function () {
                return $$Number.Uint8.maxManyExn([]);
              }));
      }));

Ava("test " + name + " addition", (function (t) {
        var testInRange = function (a, b) {
          var result = fromIntExn(a + b | 0);
          var a$1 = fromIntExn(a);
          var b$1 = fromIntExn(b);
          t.deepEqual($$Number.Uint8.add(a$1, b$1), Caml_option.some(result), undefined);
          t.deepEqual($$Number.Uint8.add(a$1, b$1), $$Number.Uint8.add(b$1, a$1), undefined);
          t.deepEqual($$Number.Uint8.addExn(a$1, b$1), result, undefined);
          t.deepEqual($$Number.Uint8.addExn(a$1, b$1), $$Number.Uint8.addExn(b$1, a$1), undefined);
          t.deepEqual($$Number.Uint8.addClamped(a$1, b$1), result, undefined);
          t.deepEqual($$Number.Uint8.addClamped(a$1, b$1), $$Number.Uint8.addClamped(b$1, a$1), undefined);
          t.deepEqual($$Number.Uint8.addUnsafe(a$1, b$1), result, undefined);
          t.deepEqual($$Number.Uint8.addUnsafe(a$1, b$1), $$Number.Uint8.addUnsafe(b$1, a$1), undefined);
          t.deepEqual($$Number.Uint8.add(a$1, zero), Caml_option.some(a$1), undefined);
          t.deepEqual($$Number.Uint8.add(a$1, zero), $$Number.Uint8.add(zero, a$1), undefined);
          t.deepEqual($$Number.Uint8.addExn(a$1, zero), a$1, undefined);
          t.deepEqual($$Number.Uint8.addExn(a$1, zero), $$Number.Uint8.addExn(zero, a$1), undefined);
          t.deepEqual($$Number.Uint8.addClamped(a$1, zero), a$1, undefined);
          t.deepEqual($$Number.Uint8.addClamped(a$1, zero), $$Number.Uint8.addClamped(zero, a$1), undefined);
          t.deepEqual($$Number.Uint8.addUnsafe(a$1, zero), a$1, undefined);
          t.deepEqual($$Number.Uint8.addUnsafe(a$1, zero), $$Number.Uint8.addUnsafe(zero, a$1), undefined);
          t.deepEqual($$Number.Uint8.add(b$1, zero), Caml_option.some(b$1), undefined);
          t.deepEqual($$Number.Uint8.add(b$1, zero), $$Number.Uint8.add(zero, b$1), undefined);
          t.deepEqual($$Number.Uint8.addExn(b$1, zero), b$1, undefined);
          t.deepEqual($$Number.Uint8.addExn(b$1, zero), $$Number.Uint8.addExn(zero, b$1), undefined);
          t.deepEqual($$Number.Uint8.addClamped(b$1, zero), b$1, undefined);
          t.deepEqual($$Number.Uint8.addClamped(b$1, zero), $$Number.Uint8.addClamped(zero, b$1), undefined);
          t.deepEqual($$Number.Uint8.addUnsafe(b$1, zero), b$1, undefined);
          t.deepEqual($$Number.Uint8.addUnsafe(b$1, zero), $$Number.Uint8.addUnsafe(zero, b$1), undefined);
        };
        testInRange(7, 27);
        testInRange(0, 0);
        testInRange(255, 0);
        testInRange(0, 1);
        var testOutOfRange = function (a, b, value) {
          var a$1 = fromIntExn(a);
          var b$1 = fromIntExn(b);
          var value$1 = fromIntExn(value);
          t.deepEqual($$Number.Uint8.add(a$1, b$1), undefined, undefined);
          t.deepEqual($$Number.Uint8.add(b$1, a$1), undefined, undefined);
          TestUtils.assertOverflow(t, (function () {
                  return $$Number.Uint8.addExn(a$1, b$1);
                }));
          TestUtils.assertOverflow(t, (function () {
                  return $$Number.Uint8.addExn(b$1, a$1);
                }));
          t.deepEqual($$Number.Uint8.addClamped(a$1, b$1), value$1, undefined);
          t.deepEqual($$Number.Uint8.addClamped(b$1, a$1), value$1, undefined);
        };
        testOutOfRange(255, 1, 255);
        testOutOfRange(255, 150, 255);
        TestUtils.loop100Fn(function () {
              var a = TestUtils.randomInt(0, 255);
              var b = TestUtils.randomInt(0, 255);
              var result = a + b;
              if (result < 0) {
                testOutOfRange(a, b, 0);
              } else if (result > 255) {
                testOutOfRange(a, b, 255);
              } else {
                testInRange(a, b);
              }
              testInRange(a, 1);
              testInRange(b, 1);
            });
      }));

Ava("test " + name + " subtraction", (function (t) {
        var testInRange = function (a, b) {
          var result = fromIntExn(a - b | 0);
          var a$1 = fromIntExn(a);
          var b$1 = fromIntExn(b);
          t.deepEqual($$Number.Uint8.sub(a$1, b$1), Caml_option.some(result), undefined);
          t.deepEqual($$Number.Uint8.subExn(a$1, b$1), result, undefined);
          t.deepEqual($$Number.Uint8.subClamped(a$1, b$1), result, undefined);
          t.deepEqual($$Number.Uint8.subUnsafe(a$1, b$1), result, undefined);
          t.deepEqual($$Number.Uint8.sub(a$1, result), Caml_option.some(b$1), undefined);
          t.deepEqual($$Number.Uint8.subExn(a$1, result), b$1, undefined);
          t.deepEqual($$Number.Uint8.subClamped(a$1, result), b$1, undefined);
          t.deepEqual($$Number.Uint8.subUnsafe(a$1, result), b$1, undefined);
          t.deepEqual($$Number.Uint8.sub(a$1, a$1), Caml_option.some(zero), undefined);
          t.deepEqual($$Number.Uint8.subExn(a$1, a$1), zero, undefined);
          t.deepEqual($$Number.Uint8.subClamped(a$1, a$1), zero, undefined);
          t.deepEqual($$Number.Uint8.subUnsafe(a$1, a$1), zero, undefined);
          t.deepEqual($$Number.Uint8.sub(a$1, zero), Caml_option.some(a$1), undefined);
          t.deepEqual($$Number.Uint8.subExn(a$1, zero), a$1, undefined);
          t.deepEqual($$Number.Uint8.subClamped(a$1, zero), a$1, undefined);
          t.deepEqual($$Number.Uint8.subUnsafe(a$1, zero), a$1, undefined);
          t.deepEqual($$Number.Uint8.sub(b$1, b$1), Caml_option.some(zero), undefined);
          t.deepEqual($$Number.Uint8.subExn(b$1, b$1), zero, undefined);
          t.deepEqual($$Number.Uint8.subClamped(b$1, b$1), zero, undefined);
          t.deepEqual($$Number.Uint8.subUnsafe(b$1, b$1), zero, undefined);
          t.deepEqual($$Number.Uint8.sub(b$1, zero), Caml_option.some(b$1), undefined);
          t.deepEqual($$Number.Uint8.subExn(b$1, zero), b$1, undefined);
          t.deepEqual($$Number.Uint8.subClamped(b$1, zero), b$1, undefined);
          t.deepEqual($$Number.Uint8.subUnsafe(b$1, zero), b$1, undefined);
        };
        testInRange(27, 7);
        testInRange(0, 0);
        testInRange(255, 0);
        testInRange(255, 1);
        var testOutOfRange = function (a, b, value) {
          var a$1 = fromIntExn(a);
          var b$1 = fromIntExn(b);
          t.deepEqual($$Number.Uint8.sub(a$1, b$1), undefined, undefined);
          TestUtils.assertOverflow(t, (function () {
                  return $$Number.Uint8.subExn(a$1, b$1);
                }));
          t.deepEqual($$Number.Uint8.subClamped(a$1, b$1), fromIntExn(value), undefined);
        };
        testOutOfRange(0, 1, 0);
        testOutOfRange(0, 150, 0);
        TestUtils.loop100Fn(function () {
              var a = TestUtils.randomInt(0, 255);
              var b = TestUtils.randomInt(0, 255);
              var result = a - b;
              if (result < 0) {
                testOutOfRange(a, b, 0);
              } else if (result > 255) {
                testOutOfRange(a, b, 255);
              } else {
                testInRange(a, b);
              }
              var result$1 = b - a;
              if (result$1 < 0) {
                return testOutOfRange(b, a, 0);
              } else if (result$1 > 255) {
                return testOutOfRange(b, a, 255);
              } else {
                return testInRange(b, a);
              }
            });
      }));

Ava("test " + name + " multiplication", (function (t) {
        var testInRange = function (a, b) {
          var result = fromIntExn(Math.imul(a, b));
          var a$1 = fromIntExn(a);
          var b$1 = fromIntExn(b);
          t.deepEqual($$Number.Uint8.mul(a$1, b$1), Caml_option.some(result), undefined);
          t.deepEqual($$Number.Uint8.mul(a$1, b$1), $$Number.Uint8.mul(b$1, a$1), undefined);
          t.deepEqual($$Number.Uint8.mulExn(a$1, b$1), result, undefined);
          t.deepEqual($$Number.Uint8.mulExn(a$1, b$1), $$Number.Uint8.mulExn(b$1, a$1), undefined);
          t.deepEqual($$Number.Uint8.mulClamped(a$1, b$1), result, undefined);
          t.deepEqual($$Number.Uint8.mulClamped(a$1, b$1), $$Number.Uint8.mulClamped(b$1, a$1), undefined);
          t.deepEqual($$Number.Uint8.mulUnsafe(a$1, b$1), result, undefined);
          t.deepEqual($$Number.Uint8.mulUnsafe(a$1, b$1), $$Number.Uint8.mulUnsafe(b$1, a$1), undefined);
          t.deepEqual($$Number.Uint8.mul(a$1, zero), Caml_option.some(zero), undefined);
          t.deepEqual($$Number.Uint8.mul(a$1, zero), $$Number.Uint8.mul(zero, a$1), undefined);
          t.deepEqual($$Number.Uint8.mulExn(a$1, zero), zero, undefined);
          t.deepEqual($$Number.Uint8.mulExn(a$1, zero), $$Number.Uint8.mulExn(zero, a$1), undefined);
          t.deepEqual($$Number.Uint8.mulClamped(a$1, zero), zero, undefined);
          t.deepEqual($$Number.Uint8.mulClamped(a$1, zero), $$Number.Uint8.mulClamped(zero, a$1), undefined);
          t.deepEqual($$Number.Uint8.mulUnsafe(a$1, zero), zero, undefined);
          t.deepEqual($$Number.Uint8.mulUnsafe(a$1, zero), $$Number.Uint8.mulUnsafe(zero, a$1), undefined);
          t.deepEqual($$Number.Uint8.mul(a$1, one), Caml_option.some(a$1), undefined);
          t.deepEqual($$Number.Uint8.mul(a$1, one), $$Number.Uint8.mul(one, a$1), undefined);
          t.deepEqual($$Number.Uint8.mulExn(a$1, one), a$1, undefined);
          t.deepEqual($$Number.Uint8.mulExn(a$1, one), $$Number.Uint8.mulExn(one, a$1), undefined);
          t.deepEqual($$Number.Uint8.mulClamped(a$1, one), a$1, undefined);
          t.deepEqual($$Number.Uint8.mulClamped(a$1, one), $$Number.Uint8.mulClamped(one, a$1), undefined);
          t.deepEqual($$Number.Uint8.mulUnsafe(a$1, one), a$1, undefined);
          t.deepEqual($$Number.Uint8.mulUnsafe(a$1, one), $$Number.Uint8.mulUnsafe(one, a$1), undefined);
          t.deepEqual($$Number.Uint8.mul(b$1, zero), Caml_option.some(zero), undefined);
          t.deepEqual($$Number.Uint8.mul(b$1, zero), $$Number.Uint8.mul(zero, b$1), undefined);
          t.deepEqual($$Number.Uint8.mulExn(b$1, zero), zero, undefined);
          t.deepEqual($$Number.Uint8.mulExn(b$1, zero), $$Number.Uint8.mulExn(zero, b$1), undefined);
          t.deepEqual($$Number.Uint8.mulClamped(b$1, zero), zero, undefined);
          t.deepEqual($$Number.Uint8.mulClamped(b$1, zero), $$Number.Uint8.mulClamped(zero, b$1), undefined);
          t.deepEqual($$Number.Uint8.mulUnsafe(b$1, zero), zero, undefined);
          t.deepEqual($$Number.Uint8.mulUnsafe(b$1, zero), $$Number.Uint8.mulUnsafe(zero, b$1), undefined);
          t.deepEqual($$Number.Uint8.mul(b$1, one), Caml_option.some(b$1), undefined);
          t.deepEqual($$Number.Uint8.mul(b$1, one), $$Number.Uint8.mul(one, b$1), undefined);
          t.deepEqual($$Number.Uint8.mulExn(b$1, one), b$1, undefined);
          t.deepEqual($$Number.Uint8.mulExn(b$1, one), $$Number.Uint8.mulExn(one, b$1), undefined);
          t.deepEqual($$Number.Uint8.mulClamped(b$1, one), b$1, undefined);
          t.deepEqual($$Number.Uint8.mulClamped(b$1, one), $$Number.Uint8.mulClamped(one, b$1), undefined);
          t.deepEqual($$Number.Uint8.mulUnsafe(b$1, one), b$1, undefined);
          t.deepEqual($$Number.Uint8.mulUnsafe(b$1, one), $$Number.Uint8.mulUnsafe(one, b$1), undefined);
        };
        testInRange(7, 27);
        testInRange(0, 0);
        testInRange(255, 0);
        testInRange(0, 1);
        testInRange(255, 1);
        testInRange(1, 1);
        testInRange(254, 1);
        var testOutOfRange = function (a, b, value) {
          var a$1 = fromIntExn(a);
          var b$1 = fromIntExn(b);
          var value$1 = fromIntExn(value);
          t.deepEqual($$Number.Uint8.mul(a$1, b$1), undefined, undefined);
          t.deepEqual($$Number.Uint8.mul(b$1, a$1), undefined, undefined);
          TestUtils.assertOverflow(t, (function () {
                  return $$Number.Uint8.mulExn(a$1, b$1);
                }));
          TestUtils.assertOverflow(t, (function () {
                  return $$Number.Uint8.mulExn(b$1, a$1);
                }));
          t.deepEqual($$Number.Uint8.mulClamped(a$1, b$1), value$1, undefined);
          t.deepEqual($$Number.Uint8.mulClamped(b$1, a$1), value$1, undefined);
        };
        testOutOfRange(255, 2, 255);
        testOutOfRange(255, 150, 255);
        TestUtils.loop100Fn(function () {
              var a = TestUtils.randomInt(0, 255);
              var b = TestUtils.randomInt(0, 255);
              var result = a * b;
              if (result < 0) {
                return testOutOfRange(a, b, 0);
              } else if (result > 255) {
                return testOutOfRange(a, b, 255);
              } else {
                return testInRange(a, b);
              }
            });
      }));

Ava("test " + name + " division", (function (t) {
        var testNotDividedByZero = function (a, b) {
          if (a !== 0) {
            var result = fromIntExn(Caml_int32.div(b, a));
            var a$1 = fromIntExn(a);
            var b$1 = fromIntExn(b);
            t.deepEqual($$Number.Uint8.div(b$1, a$1), Caml_option.some(result), undefined);
            t.deepEqual($$Number.Uint8.divExn(b$1, a$1), result, undefined);
            t.deepEqual($$Number.Uint8.divUnsafe(b$1, a$1), result, undefined);
            t.deepEqual($$Number.Uint8.div(a$1, a$1), Caml_option.some(one), undefined);
            t.deepEqual($$Number.Uint8.divExn(a$1, a$1), one, undefined);
            t.deepEqual($$Number.Uint8.divUnsafe(a$1, a$1), one, undefined);
            t.deepEqual($$Number.Uint8.div(zero, a$1), Caml_option.some(zero), undefined);
            t.deepEqual($$Number.Uint8.divExn(zero, a$1), zero, undefined);
            t.deepEqual($$Number.Uint8.divUnsafe(zero, a$1), zero, undefined);
          }
          if (b !== 0) {
            var result$1 = fromIntExn(Caml_int32.div(a, b));
            var a$2 = fromIntExn(a);
            var b$2 = fromIntExn(b);
            t.deepEqual($$Number.Uint8.div(a$2, b$2), Caml_option.some(result$1), undefined);
            t.deepEqual($$Number.Uint8.divExn(a$2, b$2), result$1, undefined);
            t.deepEqual($$Number.Uint8.divUnsafe(a$2, b$2), result$1, undefined);
            t.deepEqual($$Number.Uint8.div(b$2, b$2), Caml_option.some(one), undefined);
            t.deepEqual($$Number.Uint8.divExn(b$2, b$2), one, undefined);
            t.deepEqual($$Number.Uint8.divUnsafe(b$2, b$2), one, undefined);
            t.deepEqual($$Number.Uint8.div(zero, b$2), Caml_option.some(zero), undefined);
            t.deepEqual($$Number.Uint8.divExn(zero, b$2), zero, undefined);
            t.deepEqual($$Number.Uint8.divUnsafe(zero, b$2), zero, undefined);
          }
          var a$3 = fromIntExn(a);
          var b$3 = fromIntExn(b);
          t.deepEqual($$Number.Uint8.div(a$3, one), Caml_option.some(a$3), undefined);
          t.deepEqual($$Number.Uint8.divExn(a$3, one), a$3, undefined);
          t.deepEqual($$Number.Uint8.divUnsafe(a$3, one), a$3, undefined);
          t.deepEqual($$Number.Uint8.div(b$3, one), Caml_option.some(b$3), undefined);
          t.deepEqual($$Number.Uint8.divExn(b$3, one), b$3, undefined);
          t.deepEqual($$Number.Uint8.divUnsafe(b$3, one), b$3, undefined);
        };
        testNotDividedByZero(0, 150);
        testNotDividedByZero(negZero, 150);
        testNotDividedByZero(7, 27);
        testNotDividedByZero(0, 7);
        testNotDividedByZero(0, 27);
        testNotDividedByZero(255, 7);
        testNotDividedByZero(255, 27);
        testNotDividedByZero(7, 2);
        testNotDividedByZero(27, 2);
        testNotDividedByZero(0, 2);
        testNotDividedByZero(255, 2);
        testNotDividedByZero(1, 2);
        testNotDividedByZero(254, 2);
        var testDividedByZero = function (i) {
          var a = fromIntExn(i);
          t.deepEqual($$Number.Uint8.div(a, zero), undefined, undefined);
          TestUtils.assertDivisionByZero(t, (function () {
                  return $$Number.Uint8.divExn(a, zero);
                }));
          var negZero$1 = fromIntExn(negZero);
          t.deepEqual($$Number.Uint8.div(a, negZero$1), undefined, undefined);
          TestUtils.assertDivisionByZero(t, (function () {
                  return $$Number.Uint8.divExn(a, negZero$1);
                }));
        };
        testFn(testDividedByZero);
        TestUtils.loop100Fn(function () {
              var a = TestUtils.randomInt(0, 255);
              var b = TestUtils.randomInt(0, 255);
              testNotDividedByZero(a, b);
              testDividedByZero(a);
              testDividedByZero(b);
            });
      }));

Ava("test " + name + " remainder", (function (t) {
        var testNotModByZero = function (a, b) {
          if (a !== 0) {
            var result = fromIntExn(Caml_int32.mod_(b, a) | 0);
            var a$1 = fromIntExn(a);
            var b$1 = fromIntExn(b);
            t.deepEqual($$Number.Uint8.rem(b$1, a$1), Caml_option.some(result), undefined);
            t.deepEqual($$Number.Uint8.remExn(b$1, a$1), result, undefined);
            t.deepEqual($$Number.Uint8.remUnsafe(b$1, a$1), result, undefined);
            t.deepEqual($$Number.Uint8.rem(zero, a$1), Caml_option.some(zero), undefined);
            t.deepEqual($$Number.Uint8.remExn(zero, a$1), zero, undefined);
            t.deepEqual($$Number.Uint8.remUnsafe(zero, a$1), zero, undefined);
          }
          if (b !== 0) {
            var result$1 = fromIntExn(Caml_int32.mod_(a, b) | 0);
            var a$2 = fromIntExn(a);
            var b$2 = fromIntExn(b);
            t.deepEqual($$Number.Uint8.rem(a$2, b$2), Caml_option.some(result$1), undefined);
            t.deepEqual($$Number.Uint8.remExn(a$2, b$2), result$1, undefined);
            t.deepEqual($$Number.Uint8.remUnsafe(a$2, b$2), result$1, undefined);
            t.deepEqual($$Number.Uint8.rem(zero, b$2), Caml_option.some(zero), undefined);
            t.deepEqual($$Number.Uint8.remExn(zero, b$2), zero, undefined);
            t.deepEqual($$Number.Uint8.remUnsafe(zero, b$2), zero, undefined);
          }
          var a$3 = fromIntExn(a);
          var b$3 = fromIntExn(b);
          t.deepEqual($$Number.Uint8.rem(a$3, one), Caml_option.some(zero), undefined);
          t.deepEqual($$Number.Uint8.remExn(a$3, one), zero, undefined);
          t.deepEqual($$Number.Uint8.remUnsafe(a$3, one), zero, undefined);
          t.deepEqual($$Number.Uint8.rem(b$3, one), Caml_option.some(zero), undefined);
          t.deepEqual($$Number.Uint8.remExn(b$3, one), zero, undefined);
          t.deepEqual($$Number.Uint8.remUnsafe(b$3, one), zero, undefined);
        };
        testNotModByZero(7, 27);
        testNotModByZero(0, 7);
        testNotModByZero(0, 27);
        testNotModByZero(255, 7);
        testNotModByZero(255, 27);
        testNotModByZero(7, 2);
        testNotModByZero(27, 2);
        testNotModByZero(0, 2);
        testNotModByZero(255, 2);
        testNotModByZero(1, 2);
        testNotModByZero(254, 2);
        var testModByZero = function (a) {
          var a$1 = fromIntExn(a);
          t.deepEqual($$Number.Uint8.rem(a$1, zero), undefined, undefined);
          TestUtils.assertDivisionByZero(t, (function () {
                  return $$Number.Uint8.remExn(a$1, zero);
                }));
          var negZero$1 = fromIntExn(negZero);
          t.deepEqual($$Number.Uint8.rem(a$1, negZero$1), undefined, undefined);
          TestUtils.assertDivisionByZero(t, (function () {
                  return $$Number.Uint8.remExn(a$1, negZero$1);
                }));
        };
        testFn(testModByZero);
        TestUtils.loop100Fn(function () {
              var a = TestUtils.randomInt(0, 255);
              var b = TestUtils.randomInt(0, 255);
              testNotModByZero(a, b);
              testModByZero(a);
              testModByZero(b);
            });
      }));

Ava("test " + name + " sum", (function (t) {
        var testInRange = function (arr) {
          var result = fromIntExn(Belt_Array.reduce(arr, 0, (function (acc, v) {
                      return acc + v | 0;
                    })));
          var arr$1 = Belt_Array.mapU(arr, (function (i) {
                  return fromIntExn(i);
                }));
          t.deepEqual($$Number.Uint8.sum(arr$1), Caml_option.some(result), undefined);
          t.deepEqual($$Number.Uint8.sumExn(arr$1), result, undefined);
          t.deepEqual($$Number.Uint8.sumUnsafe(arr$1), result, undefined);
        };
        testInRange([7]);
        testInRange([27]);
        testInRange([0]);
        testInRange([255]);
        testInRange([1]);
        testInRange([254]);
        testInRange([
              7,
              27
            ]);
        testInRange([
              27,
              7
            ]);
        testInRange([
              7,
              0,
              150,
              1,
              27
            ]);
        testInRange([
              0,
              255
            ]);
        t.deepEqual($$Number.Uint8.sum([]), undefined, undefined);
        TestUtils.assertInvalidArgument(t, (function () {
                return $$Number.Uint8.sumExn([]);
              }));
        var testOutOfRange = function (arr) {
          var arr$1 = Belt_Array.mapU(arr, (function (i) {
                  return fromIntExn(i);
                }));
          t.deepEqual($$Number.Uint8.sum(arr$1), undefined, undefined);
          TestUtils.assertOverflow(t, (function () {
                  return $$Number.Uint8.sumExn(arr$1);
                }));
        };
        testOutOfRange([
              255,
              1
            ]);
        testOutOfRange([
              1,
              255
            ]);
        testOutOfRange([
              255,
              150
            ]);
        testOutOfRange([
              150,
              255
            ]);
        testOutOfRange([
              255,
              20,
              150
            ]);
        TestUtils.loop100Fn(function () {
              var a = TestUtils.randomInt(0, 255);
              var b = TestUtils.randomInt(0, 255);
              testInRange([a]);
              testInRange([b]);
              var result = a + b;
              if (result >= 0 && result <= 255) {
                testInRange([
                      a,
                      b
                    ]);
                return testInRange([
                            b,
                            a
                          ]);
              } else {
                testOutOfRange([
                      a,
                      b
                    ]);
                return testOutOfRange([
                            b,
                            a
                          ]);
              }
            });
      }));

Ava("test " + name + " increase and decrease", (function (t) {
        var testIncInRange = function (i) {
          var result = fromIntExn(i + 1 | 0);
          var n = fromIntExn(i);
          t.deepEqual($$Number.Uint8.inc(n), Caml_option.some(result), undefined);
          t.deepEqual($$Number.Uint8.incExn(n), result, undefined);
          t.deepEqual($$Number.Uint8.incUnsafe(n), result, undefined);
        };
        testIncInRange(0);
        testIncInRange(1);
        testIncInRange(150);
        testIncInRange(0);
        testIncInRange(1);
        testIncInRange(254);
        TestUtils.loop100Fn(function () {
              testIncInRange(TestUtils.randomInt(0, 255));
            });
        t.deepEqual($$Number.Uint8.inc($$Number.Uint8.maxValue), undefined, undefined);
        TestUtils.assertOverflow(t, (function () {
                return $$Number.Uint8.incExn($$Number.Uint8.maxValue);
              }));
        var testDecInRange = function (i) {
          var result = fromIntExn(i - 1 | 0);
          var n = fromIntExn(i);
          t.deepEqual($$Number.Uint8.dec(n), Caml_option.some(result), undefined);
          t.deepEqual($$Number.Uint8.decExn(n), result, undefined);
          t.deepEqual($$Number.Uint8.decUnsafe(n), result, undefined);
        };
        testDecInRange(1);
        testDecInRange(150);
        testDecInRange(1);
        testDecInRange(255);
        testDecInRange(254);
        TestUtils.loop100Fn(function () {
              testDecInRange(TestUtils.randomInt(0 + 1.0, 255));
            });
        t.deepEqual($$Number.Uint8.dec($$Number.Uint8.minValue), undefined, undefined);
        TestUtils.assertOverflow(t, (function () {
                return $$Number.Uint8.decExn($$Number.Uint8.minValue);
              }));
      }));

Ava("test " + name + " bitwise", (function (t) {
        var assertNot1 = function (a, b) {
          var a$1 = fromIntExn(a);
          var b$1 = fromIntExn(b);
          t.deepEqual($$Number.Uint8.lnot(a$1), b$1, undefined);
          t.deepEqual($$Number.Uint8.lnot(b$1), a$1, undefined);
        };
        assertNot1(150, 105);
        assertNot1(0, 255);
        assertNot1(1, 254);
        var assertNot2 = function (i) {
          var n = fromIntExn(i);
          t.deepEqual($$Number.Uint8.lnot($$Number.Uint8.lnot(n)), n, undefined);
        };
        testFn(assertNot2);
        var assertAnd = function (a, b, value) {
          var a$1 = fromIntExn(a);
          var b$1 = fromIntExn(b);
          var value$1 = fromIntExn(value);
          t.deepEqual($$Number.Uint8.land(a$1, a$1), a$1, undefined);
          t.deepEqual($$Number.Uint8.land(b$1, b$1), b$1, undefined);
          t.deepEqual($$Number.Uint8.land(value$1, value$1), value$1, undefined);
          t.deepEqual($$Number.Uint8.land(a$1, $$Number.Uint8.lnot(a$1)), zero, undefined);
          t.deepEqual($$Number.Uint8.land(b$1, $$Number.Uint8.lnot(b$1)), zero, undefined);
          t.deepEqual($$Number.Uint8.land(value$1, $$Number.Uint8.lnot(value$1)), zero, undefined);
          t.deepEqual($$Number.Uint8.land(a$1, b$1), value$1, undefined);
          t.deepEqual($$Number.Uint8.land(b$1, a$1), value$1, undefined);
        };
        assertAnd(150, 105, 0);
        assertAnd(0, 255, 0);
        assertAnd(1, 254, 0);
        assertAnd(7, 27, 3);
        TestUtils.loop100Fn(function () {
              var value = TestUtils.randomInt(0, 255);
              assertAnd(value, value, value);
            });
        var assertOr = function (a, b, value) {
          var a$1 = fromIntExn(a);
          var b$1 = fromIntExn(b);
          var value$1 = fromIntExn(value);
          var oneBits = $$Number.Uint8.maxValue;
          t.deepEqual($$Number.Uint8.lor(a$1, a$1), a$1, undefined);
          t.deepEqual($$Number.Uint8.lor(b$1, b$1), b$1, undefined);
          t.deepEqual($$Number.Uint8.lor(value$1, value$1), value$1, undefined);
          t.deepEqual($$Number.Uint8.lor(a$1, $$Number.Uint8.lnot(a$1)), oneBits, undefined);
          t.deepEqual($$Number.Uint8.lor(b$1, $$Number.Uint8.lnot(b$1)), oneBits, undefined);
          t.deepEqual($$Number.Uint8.lor(value$1, $$Number.Uint8.lnot(value$1)), oneBits, undefined);
          t.deepEqual($$Number.Uint8.lor(a$1, b$1), value$1, undefined);
          t.deepEqual($$Number.Uint8.lor(b$1, a$1), value$1, undefined);
        };
        assertOr(7, 27, 31);
        TestUtils.loop100Fn(function () {
              var value = TestUtils.randomInt(0, 255);
              assertOr(value, value, value);
            });
        assertOr(150, 105, 255);
        assertOr(0, 255, 255);
        assertOr(1, 254, 255);
        var assertXor = function (a, b, value) {
          var a$1 = fromIntExn(a);
          var b$1 = fromIntExn(b);
          var value$1 = fromIntExn(value);
          var oneBits = $$Number.Uint8.maxValue;
          t.deepEqual($$Number.Uint8.lxor(a$1, a$1), zero, undefined);
          t.deepEqual($$Number.Uint8.lxor(b$1, b$1), zero, undefined);
          t.deepEqual($$Number.Uint8.lxor(value$1, value$1), zero, undefined);
          t.deepEqual($$Number.Uint8.lxor(a$1, $$Number.Uint8.lnot(a$1)), oneBits, undefined);
          t.deepEqual($$Number.Uint8.lxor(b$1, $$Number.Uint8.lnot(b$1)), oneBits, undefined);
          t.deepEqual($$Number.Uint8.lxor(value$1, $$Number.Uint8.lnot(value$1)), oneBits, undefined);
          t.deepEqual($$Number.Uint8.lxor(a$1, b$1), value$1, undefined);
          t.deepEqual($$Number.Uint8.lxor(b$1, a$1), value$1, undefined);
        };
        assertXor(7, 27, 28);
        TestUtils.loop100Fn(function () {
              var value = TestUtils.randomInt(0, 255);
              assertXor(value, value, 0);
            });
        assertXor(150, 105, 255);
        assertXor(0, 255, 255);
        assertXor(1, 254, 255);
        var modBits = function (i) {
          return ((i >>> 0) % bits);
        };
        var value = fromIntExn(150);
        for(var i = -8; i <= 16; ++i){
          t.deepEqual($$Number.Uint8.lsl(value, i), fromIntExn(Belt_Array.getExn(valueShiftLeft, modBits(i))), undefined);
        }
        var mask = 255;
        var testUnsignedShiftRight = function (value) {
          var n = fromIntExn(value);
          for(var i = -8; i <= 16; ++i){
            var i_ = modBits(i);
            t.deepEqual($$Number.Uint8.lsr(n, i), fromFloatExn(Math.floor((
                          value < 0 && i_ !== 0 ? value & mask : value
                        ) / Math.pow(2.0, i_))), undefined);
          }
        };
        testUnsignedShiftRight(150);
        testUnsignedShiftRight(105);
        TestUtils.loop100Fn(function () {
              testUnsignedShiftRight(TestUtils.randomInt(0, 255));
            });
        var testShiftRight = function (value) {
          var n = fromIntExn(value);
          for(var i = -8; i <= 16; ++i){
            t.deepEqual($$Number.Uint8.asr(n, i), fromFloatExn(Math.floor(value / Math.pow(2.0, modBits(i)))), undefined);
          }
        };
        testShiftRight(150);
        testShiftRight(105);
        TestUtils.loop100Fn(function () {
              testShiftRight(TestUtils.randomInt(0, 255));
            });
        var value$1 = fromIntExn(150);
        for(var i$1 = -8; i$1 <= 16; ++i$1){
          t.deepEqual($$Number.Uint8.rsl(value$1, i$1), fromIntExn(Belt_Array.getExn(valueRotateShiftLeft, modBits(i$1))), undefined);
        }
        var testRotateShiftLeft = function (value) {
          var n = fromIntExn(value);
          for(var i = -8; i <= 16; ++i){
            t.deepEqual($$Number.Uint8.lnot($$Number.Uint8.rsl(n, i)), $$Number.Uint8.rsl($$Number.Uint8.lnot(n), i), undefined);
          }
        };
        testRotateShiftLeft(150);
        testRotateShiftLeft(105);
        TestUtils.loop100Fn(function () {
              testRotateShiftLeft(TestUtils.randomInt(0, 255));
            });
        var testRotateShiftRight = function (value) {
          var n = fromIntExn(value);
          for(var i = -8; i <= 16; ++i){
            t.deepEqual($$Number.Uint8.rsl(n, i), $$Number.Uint8.rsr(n, 8 - i | 0), undefined);
            t.deepEqual($$Number.Uint8.lnot($$Number.Uint8.rsr(n, i)), $$Number.Uint8.rsr($$Number.Uint8.lnot(n), i), undefined);
          }
        };
        testRotateShiftRight(150);
        testRotateShiftRight(105);
        TestUtils.loop100Fn(function () {
              testRotateShiftRight(TestUtils.randomInt(0, 255));
            });
      }));

Ava("test " + name + " integer math", (function (t) {
        var testClz = function (n, result) {
          t.deepEqual($$Number.Uint8.clz(n), result, undefined);
        };
        testClz(zero, 8);
        testClz($$Number.Uint8.minValue, 8);
        testClz($$Number.Uint8.maxValue, 0);
        for(var i = 0; i <= 7; ++i){
          testClz($$Number.Uint8.lsl(one, i), (8 - i | 0) - 1 | 0);
        }
        t.deepEqual($$Number.Uint8.imul(fromIntExn(7), fromIntExn(27)), fromIntExn(189), undefined);
        var mask = 255;
        var j = Math.pow(2.0, 8);
        var k = Math.pow(2.0, 7);
        var toU32 = function (i) {
          return TestUtils.intToUint32(i & mask);
        };
        TestUtils.loop100Fn(function () {
              var a = TestUtils.randomInt(0, 255);
              var b = TestUtils.randomInt(0, 255);
              var m = toU32(a) * toU32(b) % j;
              var result = false && m >= k ? m - j : m;
              t.deepEqual($$Number.Uint8.imul(fromIntExn(a), fromIntExn(b)), fromFloatExn(result), undefined);
              t.deepEqual($$Number.Uint8.imul(fromIntExn(b), fromIntExn(a)), fromFloatExn(result), undefined);
            });
        var testPowInRange = function (a, b) {
          var result = fromFloatExn(Math.pow(a, b));
          var a$1 = fromIntExn(a);
          var b$1 = fromIntExn(b);
          t.deepEqual($$Number.Uint8.pow(a$1, b$1), Caml_option.some(result), undefined);
          t.deepEqual($$Number.Uint8.powExn(a$1, b$1), result, undefined);
          t.deepEqual($$Number.Uint8.powUnsafe(a$1, b$1), result, undefined);
          t.deepEqual($$Number.Uint8.pow(a$1, zero), Caml_option.some(one), undefined);
          t.deepEqual($$Number.Uint8.powExn(a$1, zero), one, undefined);
          t.deepEqual($$Number.Uint8.powUnsafe(a$1, zero), one, undefined);
          t.deepEqual($$Number.Uint8.pow(b$1, zero), Caml_option.some(one), undefined);
          t.deepEqual($$Number.Uint8.powExn(b$1, zero), one, undefined);
          t.deepEqual($$Number.Uint8.powUnsafe(b$1, zero), one, undefined);
          t.deepEqual($$Number.Uint8.pow(a$1, one), Caml_option.some(a$1), undefined);
          t.deepEqual($$Number.Uint8.powExn(a$1, one), a$1, undefined);
          t.deepEqual($$Number.Uint8.powUnsafe(a$1, one), a$1, undefined);
          t.deepEqual($$Number.Uint8.pow(b$1, one), Caml_option.some(b$1), undefined);
          t.deepEqual($$Number.Uint8.powExn(b$1, one), b$1, undefined);
          t.deepEqual($$Number.Uint8.powUnsafe(b$1, one), b$1, undefined);
        };
        testPowInRange(0, 1);
        testPowInRange(1, 0);
        testPowInRange(150, 0);
        testPowInRange(0, 1);
        testPowInRange(255, 1);
        var testPowOutOfRange = function (a, b) {
          var a$1 = fromIntExn(a);
          var b$1 = fromIntExn(b);
          t.deepEqual($$Number.Uint8.pow(a$1, b$1), undefined, undefined);
          TestUtils.assertOverflow(t, (function () {
                  return $$Number.Uint8.powExn(a$1, b$1);
                }));
        };
        testPowOutOfRange(255, 2);
        testPowInRange(0, 150);
        TestUtils.loop100Fn(function () {
              var a = TestUtils.randomInt(0, 255);
              var b = TestUtils.randomPositiveSmallInt();
              var result = Math.pow(a, b);
              if (result >= 0 && result <= 255) {
                return testPowInRange(a, b);
              } else {
                return testPowOutOfRange(a, b);
              }
            });
        TestUtils.loop100Fn(function () {
              var m = TestUtils.randomInt(0, 255);
              var n = TestUtils.randomInt(0, 255);
              var min = fromIntExn(m < n ? m : n);
              var max = fromIntExn(m > n ? m : n);
              if (min !== max) {
                return TestUtils.loopFn((function () {
                              var i = $$Number.Uint8.random(min, max);
                              t.true($$Number.Uint8.ge(i, min), undefined);
                              t.true($$Number.Uint8.lt(i, max), undefined);
                            }), 10);
              }
              
            });
      }));

var IntModule;

var isSigned = false;

var is32Bits = false;

var bits = 8;

var minValue = 0;

var maxValue = 255;

var value = 150;

var valueNot = 105;

var less = 7;

var greater = 27;

var lessGreaterAnd = 3;

var lessGreaterOr = 31;

var lessGreaterXor = 28;

export {
  IntModule ,
  name ,
  isSigned ,
  is32Bits ,
  bits ,
  minValue ,
  maxValue ,
  value ,
  valueNot ,
  valueShiftLeft ,
  valueRotateShiftLeft ,
  less ,
  greater ,
  lessGreaterAnd ,
  lessGreaterOr ,
  lessGreaterXor ,
  negZero ,
  zero ,
  one ,
  fromIntExn ,
  fromFloatExn ,
  randomValue ,
  randomLargerInt ,
  randomSmallerInt ,
  testFn ,
}
/*  Not a pure module */
