// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ResNumber__Float from "./ResNumber__Float.bs.mjs";
import * as ResNumber__Integer from "./ResNumber__Integer.bs.mjs";
import * as ResNumber__Operation from "./ResNumber__Operation.bs.mjs";

var Float64 = ResNumber__Float.Float64;

var MakeIntegerConversion = ResNumber__Integer.MakeIntegerConversion;

var MakeNumberIncDec = ResNumber__Integer.MakeNumberIncDec;

var MakeInteger = ResNumber__Integer.MakeInteger;

var MakeFixedBitsIntegerConversion = ResNumber__Integer.MakeFixedBitsIntegerConversion;

var MakeFixedBitsInt = ResNumber__Integer.MakeFixedBitsInt;

var MakeIntegerMath = ResNumber__Integer.MakeIntegerMath;

var MakeFixedBitsInteger = ResNumber__Integer.MakeFixedBitsInteger;

var MakeSignedInteger = ResNumber__Integer.MakeSignedInteger;

var MakeUnsignedInteger = ResNumber__Integer.MakeUnsignedInteger;

var Int8 = ResNumber__Integer.Int8;

var Uint8 = ResNumber__Integer.Uint8;

var Int16 = ResNumber__Integer.Int16;

var Uint16 = ResNumber__Integer.Uint16;

var Int32 = ResNumber__Integer.Int32;

var Uint32 = ResNumber__Integer.Uint32;

var MakeNumberSum = ResNumber__Operation.MakeNumberSum;

export {
  Float64 ,
  MakeIntegerConversion ,
  MakeNumberIncDec ,
  MakeInteger ,
  MakeFixedBitsIntegerConversion ,
  MakeFixedBitsInt ,
  MakeIntegerMath ,
  MakeFixedBitsInteger ,
  MakeSignedInteger ,
  MakeUnsignedInteger ,
  Int8 ,
  Uint8 ,
  Int16 ,
  Uint16 ,
  Int32 ,
  Uint32 ,
  MakeNumberSum ,
}
/* ResNumber__Float Not a pure module */
