// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ResNumber__Float from "./ResNumber__Float.bs.mjs";
import * as ResNumber__Others from "./ResNumber__Others.bs.mjs";
import * as ResNumber__Integer from "./ResNumber__Integer.bs.mjs";

var NumberOverflow = ResNumber__Others.NumberOverflow;

var MakeInteger;

var MakeSignedInteger;

var MakeUnsignedInteger;

var Int8 = ResNumber__Integer.Int8;

var Uint8 = ResNumber__Integer.Uint8;

var Int16 = ResNumber__Integer.Int16;

var Uint16 = ResNumber__Integer.Uint16;

var Int32 = ResNumber__Integer.Int32;

var Uint32 = ResNumber__Integer.Uint32;

var Float64 = ResNumber__Float.Float64;

export {
  NumberOverflow ,
  MakeInteger ,
  MakeSignedInteger ,
  MakeUnsignedInteger ,
  Int8 ,
  Uint8 ,
  Int16 ,
  Uint16 ,
  Int32 ,
  Uint32 ,
  Float64 ,
}
/* ResNumber__Float Not a pure module */
